### ISSUE TITLE
Sending non-new, unmodified files

### ISSUE THREAD

**Issue by oliveriojnn** [rclone/rclone#1691]
I'm really enjoying the rclone, but I found maybe a bug.

Whenever I give a rclone copy source dest it sends some files (about 2gb), however they are not new or modified.

Can you tell why this is happening?

**Comment by breunigs** [comment]
Can you please re-run the copy, buy append `-vv` as options, so we get a more detailed debug output? Also, from where to where are you copying?

**Comment by oliveriojnn** [comment]
I just ran this command:

`rclone copy -vv WORKS \ 2016 / 'mirai: / Redacao2-Ipsep / WORKS 2016 /'> ~ / rclone.log 2> & 1`

As soon as I finish I share rclone.log here

**Comment by oliveriojnn** [comment]
https://s3.us-east-2.amazonaws.com/oliverio/rclone.log

Ready. Concluded!

This time I put another directory, but even so he even transferred 13mb, different from the other directory that transfers 2gb every time I run a copy.

Strange is that there was no file modification and no new file in the directory.

**Comment by oliveriojnn** [comment]
https://gist.github.com/oliveriojnn/e85674e7993b24e3ddc81464dae10619

Here is the moment he sends the files.

If I run the same command again it will send those same files again. Even though they are not altered and added.

**Comment by ncw** [comment]
I suspect file name normalisation... Try the latest beta

**Comment by oliveriojnn** [comment]
Hmm..

Do you want me to show the logs from another larger directory?

**Comment by breunigs** [comment]
From the same directory would be fine, but try the most recent development version of rclone: https://beta.rclone.org/

It contains some fixes which also might solve your issue. of course, if it still fails please do post the logs!

**Comment by barnabyc** [comment]
I found this issue as I was having the same problem, and seemed like name normalization issues. (Files with accents and umluts in their names would always re-download.)

I grabbed the `rclone-v1.37-157-g5a3a56abβ-linux-amd64` beta build and left it running last night, looked to be running well and fixed the issue, but then my logged filled with:

```
goroutine 124737 [chan send, 6 minutes]:
github.com/ncw/rclone/fs.(*march).run.func1.1(0xc42078ee00, 0x1e, 0x20, 0xc4203802a0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march.go:143 +0xde
created by github.com/ncw/rclone/fs.(*march).run.func1
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march.go:139 +0x289

goroutine 124959 [IO wait]:
internal/poll.runtime_pollWait(0x7fc2e002daf0, 0x72, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42992a418, 0x72, 0xffffffffffffff00, 0x13cd3e0, 0x13c6558)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42992a418, 0xc42a605000, 0x1000, 0x1000)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42992a400, 0xc42a605000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42992a400, 0xc42a605000, 0x1000, 0x1000, 0x7109084e3c7, 0x142f640, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420570078, 0xc42a605000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/net.go:176 +0x6d
net.(Conn).Read-fm(0xc42a605000, 0x1000, 0x1000, 0x410907, 0xc4208360f0, 0x10)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/http.go:84 +0x4d
github.com/ncw/rclone/fs.(*timeoutConn).readOrWrite(0xc420c96b80, 0xc42032f758, 0xc42a605000, 0x1000, 0x1000, 0xc4205d4380, 0x7fc2e00896c8, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/http.go:74 +0x69
github.com/ncw/rclone/fs.(*timeoutConn).Read(0xc420c96b80, 0xc42a605000, 0x1000, 0x1000, 0xe03700, 0xc420572b00, 0x7fc2dffed0a8)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/http.go:84 +0x82
crypto/tls.(*block).readFromUntil(0xc420572b70, 0x7fc2dffed0a8, 0xc420c96b80, 0x5, 0xc420c96b80, 0xc420573860)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420250e00, 0xec0117, 0xc420250f20, 0x42ccab)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420250e00, 0xc420cf6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/crypto/tls/conn.go:1134 +0x110
net/http.(*persistConn).Read(0xc420fa0480, 0xc420cf6000, 0x1000, 0x1000, 0xc421ce0020, 0xc42110c298, 0x454270)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc422aeac60)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc422aeac60, 0x1, 0x0, 0x0, 0x1, 0xc426580360, 0x0)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc420fa0480)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/http/transport.go:1186 +0xa2e
```

@ncw - I can provide more detail if that helps, wanted to let you know.
