### ISSUE TITLE
rclone mount and s3ql: Dir.Rename error: file does not exist

### ISSUE THREAD

**Issue by SteffenDE** [rclone/rclone#2275]
#### What is the problem you are having with rclone?

Using an s3ql filesystem on top of an rclone mount (Google Drive with Cache) does not work.

#### What is your rclone version (eg output from `rclone -V`)
```
rclone v1.40-116-gbe8bd896β
- os/arch: linux/amd64
- go version: go1.10.1
```
#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone mount --config /root/.config/rclone/rclone.conf --allow-other --allow-non-empty --buffer-size 100M --cache-info-age 48h --cache-db-purge --cache-writes --timeout 5s --contimeout 5s --log-file /var/log/ncdrive.log --log-level INFO --daemon ncCache: /mnt/nc_drive`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/04/24 23:36:46 INFO  : ncCache: Cache DB path: /root/.cache/rclone/cache-backend/ncCache.db
2018/04/24 23:36:46 INFO  : ncCache: Cache chunk path: /root/.cache/rclone/cache-backend/ncCache
2018/04/24 23:36:47 INFO  : ncCache: Chunk Memory: true
2018/04/24 23:36:47 INFO  : ncCache: Chunk Size: 10M
2018/04/24 23:36:47 INFO  : ncCache: Chunk Total Size: 1G
2018/04/24 23:36:47 INFO  : ncCache: Chunk Clean Interval: 1m0s
2018/04/24 23:36:47 INFO  : ncCache: Workers: 4
2018/04/24 23:36:47 INFO  : ncCache: File Age: 48h0m0s
2018/04/24 23:36:47 INFO  : ncCache: Cache Writes: enabled
2018/04/24 23:36:47 INFO  : Cache remote ncCache:: Modify window is 1ms
2018/04/24 23:36:47 INFO  : ncCache: Cache DB path: /root/.cache/rclone/cache-backend/ncCache.db
2018/04/24 23:36:47 INFO  : ncCache: Cache chunk path: /root/.cache/rclone/cache-backend/ncCache
2018/04/24 23:36:47 INFO  : ncCache: Chunk Memory: true
2018/04/24 23:36:47 INFO  : ncCache: Chunk Size: 10M
2018/04/24 23:36:47 INFO  : ncCache: Chunk Total Size: 1G
2018/04/24 23:36:47 INFO  : ncCache: Chunk Clean Interval: 1m0s
2018/04/24 23:36:47 INFO  : ncCache: Workers: 4
2018/04/24 23:36:47 INFO  : ncCache: File Age: 48h0m0s
2018/04/24 23:36:47 INFO  : ncCache: Cache Writes: enabled
2018/04/24 23:36:47 INFO  : Cache remote ncCache:: Modify window is 1ms
2018/04/24 23:37:08 ERROR : s3ql_passphrase#13456-140217174279936.tmp: Dir.Rename error: file does not exist
2018/04/24 23:37:10 INFO  : : put: cache expired
2018/04/24 23:37:10 INFO  : s3ql_passphrase#13456-140217174279936.tmp: Copied (new)
2018/04/24 23:37:48 INFO  : : received cache expiry notification
2018/04/24 23:37:48 INFO  : s3ql_passphrase#13456-140217174279936.tmp: received cache expiry notification
```

mkfs.s3ql fails:
```
root@webserver ~ # mkfs.s3ql local:///mnt/nc_drive/
Before using S3QL, make sure to read the user's guide, especially
the 'Important Rules to Avoid Loosing Data' section.
Enter encryption password: 
Confirm encryption password: 
Generating random encryption key...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mkfs.s3ql", line 9, in <module>
    load_entry_point('s3ql==2.26', 'console_scripts', 'mkfs.s3ql')()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/mkfs.py", line 131, in main
    backend['s3ql_passphrase'] = data_pw
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 265, in __setitem__
    self.store(key, value)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 368, in store
    self.perform_write(lambda fh: fh.write(val), key, metadata)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 339, in perform_write
    with self.open_write(key, metadata, is_compressed) as fh:
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/comprenc.py", line 228, in open_write
    fh = self.backend.open_write(key, meta_raw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/local.py", line 103, in open_write
    os.rename(tmpname, path)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nc_drive/s3ql_passphrase#13456-140217174279936.tmp' -> '/mnt/nc_drive/s3ql_passphrase'
```
```
root@webserver ~ # ls -la /mnt/nc_drive/
insgesamt 0
-rw-r--r-- 1 root root 0 Apr 24 23:37 s3ql_passphrase#13456-140217174279936.tmp
```
The same happens when not using the cache backend, but Google Drive directly.
```
2018/04/24 23:41:08 ERROR : s3ql_passphrase#13745-139705347577600.tmp: Dir.Rename error: file does not exist
2018/04/24 23:41:10 INFO  : s3ql_passphrase#13745-139705347577600.tmp: Copied (new)
```
```
root@webserver ~ # ls -la /mnt/nc_drive/
insgesamt 0
-rw-r--r-- 1 root root 0 Apr 24 23:41 s3ql_passphrase#13745-139705347577600.tmp
```

**Comment by SteffenDE** [comment]
I just tried the same using `--vfs-cache-mode writes` and get a different error:
```
root@webserver ~ # mkfs.s3ql local:///mnt/nc_drive/
Before using S3QL, make sure to read the user's guide, especially
the 'Important Rules to Avoid Loosing Data' section.
Enter encryption password: 
Confirm encryption password: 
Generating random encryption key...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mkfs.s3ql", line 9, in <module>
    load_entry_point('s3ql==2.26', 'console_scripts', 'mkfs.s3ql')()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/mkfs.py", line 131, in main
    backend['s3ql_passphrase'] = data_pw
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 265, in __setitem__
    self.store(key, value)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 368, in store
    self.perform_write(lambda fh: fh.write(val), key, metadata)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 339, in perform_write
    with self.open_write(key, metadata, is_compressed) as fh:
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/comprenc.py", line 228, in open_write
    fh = self.backend.open_write(key, meta_raw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.26-py3.5-linux-x86_64.egg/s3ql/backends/local.py", line 103, in open_write
    os.rename(tmpname, path)
PermissionError: [Errno 1] Operation not permitted: '/mnt/nc_drive/s3ql_passphrase#14297-140276077631232.tmp' -> '/mnt/nc_drive/s3ql_passphrase'
```
```
2018/04/24 23:48:16 ERROR : s3ql_passphrase#14297-140276077631232.tmp: Dir.Rename cant rename open file
2018/04/24 23:48:17 INFO  : : put: cache expired
2018/04/24 23:48:17 INFO  : s3ql_passphrase#14297-140276077631232.tmp: Copied (new)
```

**Comment by ncw** [comment]
> I just tried the same using --vfs-cache-mode writes and get a different error:

You almost certainly want to be using that to make a more compliant file system.

`Dir.Rename cant rename open file` is being looked at in #2249 and issue #2130

**Comment by ncw** [comment]
I'm pretty sure this will be fixed with [the latest release](https://rclone.org/downloads/) or [the latest beta](https://beta.rclone.org) and `--vfs-cache-mode writes`
