### ISSUE TITLE
Unable to run any commands on remote `panic: runtime error: index out of range`

### ISSUE THREAD

**Issue by thomasswan5547** [rclone/rclone#2802]
#### What is the problem you are having with rclone?

Unable to run any commands on my current accounts, notably `rclone mount`, commands tried `lsd`, `mount`, `ncdu` all ending with this error `panic: runtime error: index out of range`

Unable to login to new remotes with this error `2018/11/27 20:29:11 Failed to create file system for "myremote:": couldn't login: The upload target URL you are trying to access has expired. Please request a fresh one`

and this one `Mega login issue, Failed to create file system for “megatwo:”: couldn’t login: Block decryption failed`

#### What is your rclone version (output from `rclone version`)

rclone 1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 pro 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

MEGA

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Notably `rclone mount remote: :X` however no commands now work of any of my configured remotes, i can login using official clients just fine though.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

On request of ncw, here's the output of the failed command.

```C:\Users\thoma\Desktop\rclone-v1.45-windows-amd64
λ rclone.exe -vv mount megaone: :X
2018/11/28 20:54:16 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone.exe" "-vv" "mount" "megaone:" ":X"]
2018/11/28 20:54:16 DEBUG : Using config file from "C:\\Users\\thoma\\.config\\rclone\\rclone.conf"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).addFSNode(0xc00032e000, 0xc0009bbc50, 0x8, 0xc0009bbc58, 0x8, 0xc0009bbc60, 0xb, 0x0, 0xc000666a20, 0x2b, ...)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:649 +0x1543
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).getFileSystem(0xc00032e000, 0x0, 0x0)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:759 +0x363
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).Login(0xc00032e000, 0xc000032667, 0x1a, 0xc00002cb90, 0xd, 0x0, 0x0)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:500 +0x527
github.com/ncw/rclone/backend/mega.NewFs(0xc0000860a0, 0x7, 0xc0000860a0, 0x0, 0x141e8a0, 0xc000167800, 0x0, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/ncw/rclone/backend/mega/mega.go:207 +0x5a0
github.com/ncw/rclone/fs.NewFs(0xc0000860a0, 0x8, 0xe24917, 0x10bdbc0, 0x0, 0x12c60a1)
        C:/gopath/src/github.com/ncw/rclone/fs/fs.go:1050 +0xbc
github.com/ncw/rclone/cmd.newFsDir(0xc0000860a0, 0x8, 0x12e, 0xc000108000)
        C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:134 +0x54
github.com/ncw/rclone/cmd.NewFsDir(0xc000166f60, 0x2, 0x3, 0xc000166f60, 0x2)
        C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:146 +0x48
github.com/ncw/rclone/cmd/mountlib.NewMountCommand.func1(0xc000350c80, 0xc000166f60, 0x2, 0x3)
        C:/gopath/src/github.com/ncw/rclone/cmd/mountlib/mount.go:223 +0xc7
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0xc000350c80, 0xc000166de0, 0x3, 0x3, 0xc000350c80, 0xc000166de0)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf79e40, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:852 +0x304
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0xf79e40, 0xc000070058, 0x0)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/ncw/rclone/cmd.Main()
        C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:482 +0x4d
main.main()
        C:/gopath/src/github.com/ncw/rclone/rclone.go:13 +0x27

C:\Users\thoma\Desktop\rclone-v1.45-windows-amd64
λ

**Comment by ncw** [comment]
I'm pretty sure this is fixed now - please try [the latest release](https://rclone.org/downloads/) or [the latest beta](https://beta.rclone.org).
