### ISSUE TITLE
ftp serve panic

### ISSUE THREAD

**Issue by calisro** [rclone/rclone#2822]
rclone v1.45-022-gfc654a4c-beta
- os/arch: linux/amd64
- go version: go1.11.2

Seeing the ftp server crash.  Not sure why

```
2018/12/07 08:54:01 INFO  : f8c5ab85c540f34053d0: < 250 Directory changed to /master/xxxxxxxx/record
2018/12/07 08:54:01 INFO  : f8c5ab85c540f34053d0: > TYPE I
2018/12/07 08:54:01 INFO  : f8c5ab85c540f34053d0: < 200 Type set to binary
2018/12/07 08:54:01 INFO  : f8c5ab85c540f34053d0: > PORT 10,100,1,111,203,175
2018/12/07 08:54:01 INFO  : f8c5ab85c540f34053d0: Opening active data connection to 10.100.1.111:52143
2018/12/07 08:54:23 DEBUG : : NewDriver: Init driver
2018/12/07 08:54:23 DEBUG : : >NewDriver: 
2018/12/07 08:54:23 DEBUG : : Init: Init session
2018/12/07 08:54:23 DEBUG : : >Init: 
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: Connection Established
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 220 Welcome on Rclone FTP Server
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > USER xxxxx
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 331 User name ok, password required
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > PASS ****
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 230 Password ok, continue
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > PWD 
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 257 "/" is the current directory
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > CWD /master
2018/12/07 08:54:23 DEBUG : /master: ChangeDir: 
2018/12/07 08:54:23 DEBUG : /master: >ChangeDir: err = <nil>
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 250 Directory changed to /master
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > PWD 
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 257 "/master" is the current directory
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > CWD xxxxxxxx/record
2018/12/07 08:54:23 DEBUG : /master/xxxxxxxx/record: ChangeDir: 
2018/12/07 08:54:23 DEBUG : /master/xxxxxxxx/record: >ChangeDir: err = <nil>
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 250 Directory changed to /master/xxxxxxxx/record
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > TYPE I
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: < 200 Type set to binary
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: > PORT 10,100,1,111,235,91
2018/12/07 08:54:23 INFO  : 4a54fcd9c6b3918d9ca9: Opening active data connection to 10.100.1.111:60251
2018/12/07 08:54:42 INFO  : 4a0841058a42a9313aec: dial tcp 10.100.1.111:47587: connect: connection timed out
2018/12/07 08:54:42 INFO  : 4a0841058a42a9313aec: < 425 Data connection failed
2018/12/07 08:54:42 INFO  : 4a0841058a42a9313aec: > STOR schedule_20181207_085232.mkv
2018/12/07 08:54:42 INFO  : 4a0841058a42a9313aec: < 150 Data transfer starting
2018/12/07 08:54:42 DEBUG : /master/xxxxxxxx/record/schedule_20181207_085232.mkv: PutFile: append=false
2018/12/07 08:54:42 DEBUG : /master/xxxxxxxx/record/schedule_20181207_085232.mkv: OpenFile: flags=O_RDWR|O_CREATE, perm=-rw-rw----
2018/12/07 08:54:42 DEBUG : master/xxxxxxxx/record/schedule_20181207_085232.mkv: Open: flags=O_RDWR|O_CREATE
2018/12/07 08:54:42 DEBUG : master/xxxxxxxx/record/schedule_20181207_085232.mkv: >Open: fd=master/xxxxxxxx/record/schedule_20181207_085232.mkv (w), err=<nil>
2018/12/07 08:54:42 DEBUG : /master/xxxxxxxx/record/schedule_20181207_085232.mkv: >OpenFile: fd=master/xxxxxxxx/record/schedule_20181207_085232.mkv (w), err=<nil>
2018/12/07 08:54:42 DEBUG : Local file system at /data/cams: File to upload is small (0 bytes), uploading instead of streaming
2018/12/07 08:54:42 INFO  : master/xxxxxxxx/record/schedule_20181207_085232.mkv: Copied (new)
2018/12/07 08:54:42 DEBUG : /master/xxxxxxxx/record/schedule_20181207_085232.mkv: >PutFile: err = file does not exist
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4670b4]

goroutine 47 [running]:
io.copyBuffer(0x7f4e03c8f9d8, 0xc0001d6070, 0x0, 0x0, 0xc000418000, 0x8000, 0x8000, 0x11e8880, 0x0, 0x7f4e03c8f9d8)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/io/io.go:402 +0x104
io.Copy(0x7f4e03c8f9d8, 0xc0001d6070, 0x0, 0x0, 0xc0001d6070, 0xc0001d6070, 0xc0001d6070)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/io/io.go:364 +0x5a
github.com/ncw/rclone/cmd/serve/ftp.(*Driver).PutFile(0xc0001e5900, 0xc000165400, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x894d07cfca19bcf5, 0xc0000abea8)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/serve/ftp/ftp.go:355 +0x43e
github.com/ncw/rclone/vendor/github.com/goftp/server.commandStor.Execute(0xc00015d6c0, 0xc00020ca85, 0x1c)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/cmd.go:1023 +0x141
github.com/ncw/rclone/vendor/github.com/goftp/server.(*Conn).receiveLine(0xc00015d6c0, 0xc00020ca80, 0x23)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/conn.go:165 +0x169
github.com/ncw/rclone/vendor/github.com/goftp/server.(*Conn).Serve(0xc00015d6c0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/conn.go:116 +0x100
created by github.com/ncw/rclone/vendor/github.com/goftp/server.(*Server).Serve
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/server.go:263 +0x21d

```

**Comment by ncw** [comment]
I think this is a bug in the ftp server library I'm using.  Not quite sure yet, but thanks for reporting :-)

**Comment by ivandeex** [comment]
@calisro Does the problem reproduce with latest rclone?

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity
