### ISSUE TITLE
mount: tests lock up with GOMAXPROCS=1 or 2

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#3259]
As reported in #3154 the test for `cmd/mount` locks up if `GOMAXPROCS=1` or `2`

This runs fine

```
cd ~/go/src/github.com/ncw/rclone/cmd/mount
export GOMAXPROCS=4
( for i in `seq 1000`; do echo `date -Is`: Trial $i ; go test -v -verbose -count=1 ; done ) 2>&1 | tee mount.log
```

And this locks up almost immediately

```
export GOMAXPROCS=1
( for i in `seq 1000`; do echo `date -Is`: Trial $i ; go test -v -verbose -count=1 ; done ) 2>&1 | tee mount.log
```

with

```
2019-06-12T16:46:56+00:00: Trial 1
=== RUN   TestMount
=== RUN   TestMount/CacheMode=off
=== RUN   TestMount/CacheMode=off/TestTouchAndDelete
```

Mount is stuck in the kernel at this point making nasty unkillable processes.

The build issue has been worked around by setting GOMAXPROCS but the underlying issue remains.

**Comment by gary-kim** [comment]
It still does not seem to be fully fixed: <https://travis-ci.org/ncw/rclone/jobs/545340848>.
I'll try to figure out what part of the mount test is causing the issue.

**Comment by ncw** [comment]
This is certainly an improvement, but not a fix :-(

I'll re-open the issue

**Comment by cameronbraid** [comment]
Not sure if this is the issue I am running on a production server, but I have thousands (and up to hundreds of thousands after a number of days of usage) of zombie processes from rclone mount

Is the workaround purely to set GOMAXPROCS to something > 2 ?

**Comment by ncw** [comment]
> Not sure if this is the issue I am running on a production server, but I have thousands (and up to hundreds of thousands after a number of days of usage) of zombie processes from rclone mount

Are you mounting and unmounting a lot - if so then this issue describes the problem. If not then it is probably another issue.
 
> Is the workaround purely to set GOMAXPROCS to something > 2 ?

To fix this issue you actually need more CPUs I think. Setting GOMAXPROCs helps a bit but isn't a total fix.

What OS are you on? Maybe you could try `rclone cmount` which uses `cgofuse` which doesn't have this problem?

**Comment by yarikoptic** [comment]
I think we are running into the same problem on Debian package building if build host has 1 cpu/core: build locks up during testing:

```
=== RUN   TestMount
2021/01/11 15:02:21 NOTICE: Config file "/home/yaroslav/.config/rclone/rclone.conf" not found - using defaults
2021/01/11 15:02:21 mount "Local file system at /tmp/rclone155259612" "/tmp/rclonefs-mount250935435"
2021/01/11 15:02:21 mount OK
2021/01/11 15:02:21 Starting test run with cache mode off
=== RUN   TestMount/CacheMode=off
=== RUN   TestMount/CacheMode=off/TestTouchAndDelete
```
we do not (AFAIK) set any GOMAXPROC env var.  

(I have no `go` , and especially no `go test` knowledge yet :-( ) What would be the best way to instruct to skip that (and only that) test?  I guess there could be some additional `+build` tag `parallel` and then somehow exclude running those tests with it (unless explicitly known/requested to test parallel functionality)?

**Comment by yarikoptic** [comment]
FWIW, here is a full build log (courtesy of  @sanvila who made me aware of the issue) https://people.debian.org/~sanvila/build-logs/rclone/rclone_1.45-3_amd64-20210104T021522.145Z which 

<details>
<summary>includes tracebacks upon killing the hanging process (FWIW, click to expand)</summary> 

```shell
=== RUN   TestMount
2021/01/04 02:17:38 NOTICE: Config file "/build/.config/rclone/rclone.conf" not found - using defaults
2021/01/04 02:17:38 mount "Local file system at /tmp/rclone218804420" "/tmp/rclonefs-mount804338515"
2021/01/04 02:17:38 mount helper error: ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
2021/01/04 02:17:38 mount OK
2021/01/04 02:17:38 Starting test run with cache mode off
=== RUN   TestMount/CacheMode=off
=== RUN   TestMount/CacheMode=off/TestTouchAndDelete
SIGQUIT: quit
PC=0x45ffa1 m=0 sigcode=0

goroutine 5 [syscall]:
runtime.notetsleepg(0x1ab9440, 0xffffffffffffffff, 0x4012f0)
	/usr/lib/go-1.11/src/runtime/lock_futex.go:227 +0x37 fp=0xc000056788 sp=0xc000056758 pc=0x40cba7
os/signal.signal_recv(0x0)
	/usr/lib/go-1.11/src/runtime/sigqueue.go:139 +0x9c fp=0xc0000567b0 sp=0xc000056788 pc=0x444ccc
os/signal.loop()
	/usr/lib/go-1.11/src/os/signal/signal_unix.go:23 +0x22 fp=0xc0000567e0 sp=0xc0000567b0 pc=0x5ea172
runtime.goexit()
	/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x45e151
created by os/signal.init.0
	/usr/lib/go-1.11/src/os/signal/signal_unix.go:29 +0x41

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000112c00, 0x10e311f, 0x9, 0x1137d40, 0x4839a6)
	/usr/lib/go-1.11/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc000112b00)
	/usr/lib/go-1.11/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc000112b00, 0xc000243e08)
	/usr/lib/go-1.11/src/testing/testing.go:827 +0xbf
testing.runTests(0xc0001b47e0, 0x1a87970, 0x1, 0x1, 0x40db7f)
	/usr/lib/go-1.11/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc000107280, 0x0)
	/usr/lib/go-1.11/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:42 +0x13d

goroutine 28 [runnable]:
syscall.Syscall(0x1, 0x7, 0xc000190820, 0xa0, 0xa0, 0xa0, 0x0)
	/usr/lib/go-1.11/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x7, 0xc000190820, 0xa0, 0xa0, 0x5c8a7f, 0xc00000eab0, 0x7)
	/usr/lib/go-1.11/src/syscall/zsyscall_linux_amd64.go:1005 +0x5a
syscall.Write(0x7, 0xc000190820, 0xa0, 0xa0, 0xe1b3b0, 0x40, 0x48)
	/usr/lib/go-1.11/src/syscall/syscall_unix.go:191 +0x49
bazil.org/fuse.(*Conn).writeToKernel(0xc000218840, 0xc000190820, 0xa0, 0xa0, 0x0, 0x0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fuse.go:1097 +0xe1
bazil.org/fuse.(*Conn).respond(0xc000218840, 0xc000190820, 0xa0, 0xa0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fuse.go:1110 +0x56
bazil.org/fuse.(*Header).respond(0xc0000af9a0, 0xc000190820, 0xa0, 0xa0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fuse.go:313 +0x59
bazil.org/fuse.(*CreateRequest).Respond(0xc0000af9a0, 0xc00025d1e0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fuse.go:1689 +0x261
bazil.org/fuse/fs.(*Server).handleRequest(0xc000110300, 0x1266b00, 0xc0002da1c0, 0x125be40, 0xc00000eab8, 0xc000153f40, 0x1264a80, 0xc0000af9a0, 0xc00006bef8, 0x0, ...)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fs/serve.go:1116 +0x11ab
bazil.org/fuse/fs.(*Server).serve(0xc000110300, 0x1264a80, 0xc0000af9a0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fs/serve.go:878 +0x410
bazil.org/fuse/fs.(*Server).Serve.func1(0xc000110300, 0x1264a80, 0xc0000af9a0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fs/serve.go:423 +0x31e

goroutine 14 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*T).Run
	/usr/lib/go-1.11/src/testing/testing.go:878 +0x35c

goroutine 9 [chan receive]:
testing.(*T).Run(0xc000112d00, 0xc0001af380, 0xd, 0x1137d60, 0x1)
	/usr/lib/go-1.11/src/testing/testing.go:879 +0x383
github.com/ncw/rclone/cmd/mountlib/mounttest.RunTests(0xc000112c00, 0x1137d50)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/cmd/mountlib/mounttest/fs.go:54 +0x199
github.com/ncw/rclone/cmd/mount.TestMount(0xc000112c00)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/cmd/mount/mount_test.go:12 +0x37
testing.tRunner(0xc000112c00, 0x1137d40)
	/usr/lib/go-1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/go-1.11/src/testing/testing.go:878 +0x35c

goroutine 13 [chan receive]:
testing.(*T).Run(0xc000112e00, 0x10ed543, 0x12, 0x1137df8, 0x152fe73)
	/usr/lib/go-1.11/src/testing/testing.go:879 +0x383
github.com/ncw/rclone/cmd/mountlib/mounttest.RunTests.func1(0xc000112d00)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/cmd/mountlib/mounttest/fs.go:55 +0x50
testing.tRunner(0xc000112d00, 0x1137d60)
	/usr/lib/go-1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/go-1.11/src/testing/testing.go:878 +0x35c

goroutine 12 [runnable]:
syscall.Syscall(0x0, 0x7, 0xc000284000, 0x21000, 0x40, 0x21000, 0x0)
	/usr/lib/go-1.11/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc000284000, 0x21000, 0x21000, 0x5c8a7f, 0xc00000eab0, 0x7)
	/usr/lib/go-1.11/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(0x7, 0xc000284000, 0x21000, 0x21000, 0xc0001af4b0, 0x7, 0x0)
	/usr/lib/go-1.11/src/syscall/syscall_unix.go:172 +0x49
bazil.org/fuse.(*Conn).ReadRequest(0xc000218840, 0x1136f00, 0xc000110300, 0x1264a80, 0xc0000af9a0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fuse.go:552 +0xb1
bazil.org/fuse/fs.(*Server).Serve(0xc000110300, 0x125be60, 0xc0001b4be0, 0x0, 0x0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/bazil.org/fuse/fs/serve.go:414 +0x332
github.com/ncw/rclone/cmd/mount.mount.func1(0xc000110300, 0xc0001b4be0, 0xc000218840, 0xc000218c60)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/cmd/mount/mount.go:98 +0x45
created by github.com/ncw/rclone/cmd/mount.mount
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/cmd/mount/mount.go:97 +0x2e2

rax    0xca
rbx    0x1a9c080
rcx    0x45ffa3
rdx    0x0
rdi    0x1ab9440
rsi    0x80
rbp    0xc000056710
rsp    0xc0000566c8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xffffffffffffffff
r13    0x2
r14    0x1
r15    0x2
rip    0x45ffa1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
E: Build killed with signal TERM after 60 minutes of inactivity
```
</details>

**Comment by yarikoptic** [comment]
any advice on how to mitigate (exclude  the test) if not to fix, would be much appreciated by yours truly go-ignorant me.

**Comment by ncw** [comment]
Sorry about this @yarikoptic it is quite annoying and I haven't worked out the fix...  If you want to work around it you can set the environment variable `CI` to something (doesn't matter what). This will stop the test being run.

This was introduced in 08b86cc94bac448677a45a5c1528e932e62bb6a5 which was released in v1.50.0 so if you are building an earlier version then that fix won't work, though you could apply that change as a patch maybe?

**Comment by yarikoptic** [comment]
> you can set the environment variable `CI` to something (doesn't matter what). This will stop the test being run.

would that stop just that test or all?  we can easily stop running all tests, but I would hate to do that.

**Comment by yarikoptic** [comment]
oh, and my bad - https://github.com/rclone/rclone/commit/08b86cc94bac448677a45a5c1528e932e62bb6a5 is in 1.53.3 so with that we should be all set. I thought that what I was trying to build/test that recent release, but it might have been building 1.45 as we were building in stable debian... (attn @sanvila) I have ran `sbuild -d sid --arch-all rclone` on  1-cpu VM and build passed.  So the issue is "being dealt with upstream" IMHO .  Thank you @ncw !

**Comment by ncw** [comment]
Glad that is working :-)

Any flaky tests will be disabled by the environment variable `CI` but present on developers computers to give them an incentive to look into them!

**Comment by ncw** [comment]
It appears that this is a known problem in https://github.com/bazil/fuse/issues/264 or the go runtime https://github.com/golang/go/issues/21014

The solution is to run the mount in a subprocess when we are doing our end to end mount tests which seems like it should be possible.
