### ISSUE TITLE
rclone sync -vvvv 同步数据出现问题。

### ISSUE THREAD

**Issue by piaoyun** [rclone/rclone#3438]
```
goroutine 2276 [select]:
github.com/ncw/rclone/fs/march.(*March).Run.func1.1(0xc0001f3880, 0xe, 0x10, 0xc000493400, 0xc0005e4260, 0xc00045d620)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:148 +0x1a2
created by github.com/ncw/rclone/fs/march.(*March).Run.func1
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:144 +0x28b

goroutine 2562 [select]:
github.com/ncw/rclone/fs/march.(*March).Run.func1.1(0xc00001f500, 0xb, 0x10, 0xc000493400, 0xc0005e4260, 0xc00045d620)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:148 +0x1a2
created by github.com/ncw/rclone/fs/march.(*March).Run.func1
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:144 +0x28b

goroutine 2973 [select]:
github.com/ncw/rclone/fs/march.(*March).Run.func1.1(0xc00e1b8000, 0x5c, 0x92, 0xc000493400, 0xc0005e4260, 0xc00045d620)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:148 +0x1a2
created by github.com/ncw/rclone/fs/march.(*March).Run.func1
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:144 +0x28b

goroutine 3240 [select]:
github.com/ncw/rclone/fs/march.(*March).Run.func1.1(0xc0003875e0, 0x3, 0x4, 0xc000493400, 0xc0005e4260, 0xc00045d620)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:148 +0x1a2
created by github.com/ncw/rclone/fs/march.(*March).Run.func1
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:144 +0x28b
```

请问下是怎么问题呢。谢谢

**Comment by ncw** [comment]
If you look at the top of the backtrace what do you see?

I'm guessing out of memory?

**Comment by animosity22** [comment]
This looks to be stale. If you have a question, please feel free to ask on the forums and we can help out.
