### ISSUE TITLE
Google Photo's error on uploading (Panic)

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#3491]
#### What is the problem you are having with rclone?

Invalid memory address panic. 

#### What is your rclone version (output from `rclone version`)

rclone v1.49.0
- os/arch: linux/amd64
- go version: go1.12.9

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 64bit X64

####  Which cloud storage system are you using? (eg Google Drive)

Google Photos Endpoint

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

/usr/bin/rclone sync

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xcec719]

goroutine 2726 [running]:
github.com/rclone/rclone/backend/googlephotos.(*Object).Update.func1(0x203000, 0x7f6669cd3a18, 0x7f)
        /home/travis/gopath/src/github.com/rclone/rclone/backend/googlephotos/googlephotos.go:959 +0x159
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0x1, 0xc0004917d0, 0xb100000001518fe0, 0xc000c798d8, 0x40c6b8)
        /home/travis/gopath/src/github.com/rclone/rclone/fs/fs.go:1369 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc0003d8b40, 0xc0004917d0, 0x1, 0x17, 0xc000369cb8)
        /home/travis/gopath/src/github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x8b
github.com/rclone/rclone/lib/pacer.(*Pacer).CallNoRetry(...)
        /home/travis/gopath/src/github.com/rclone/rclone/lib/pacer/pacer.go:225
github.com/rclone/rclone/backend/googlephotos.(*Object).Update(0xc00038b6c0, 0x1879d60, 0xc000596a00, 0x1851a20, 0xc0022fb6c0, 0x7f6669d1fe40, 0xc00092e8a0, 0xc000074fb0, 0x1, 0x1, ...)
        /home/travis/gopath/src/github.com/rclone/rclone/backend/googlephotos/googlephotos.go:956 +0x4c5
github.com/rclone/rclone/backend/googlephotos.(*Fs).Put(0xc000562e10, 0x1879d60, 0xc000596a00, 0x1851a20, 0xc0022fb6c0, 0x7f6669d1fe40, 0xc00092e8a0, 0xc000074fb0, 0x1, 0x1, ...)
        /home/travis/gopath/src/github.com/rclone/rclone/backend/googlephotos/googlephotos.go:623 +0x1f0
github.com/rclone/rclone/fs/operations.Copy(0x1879d60, 0xc000596a00, 0x188e2a0, 0xc000562e10, 0x0, 0xc0004b77a0, 0xc000dba51f, 0x20, 0x188e7a0, 0xc00092e8a0, ...)
        /home/travis/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:358 +0x1415
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000315c00, 0x1879d60, 0xc000596a00, 0xc000596840, 0x188e2a0, 0xc000562e10, 0xc000315cd8)
        /home/travis/gopath/src/github.com/rclone/rclone/fs/sync/sync.go:297 +0x206
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        /home/travis/gopath/src/github.com/rclone/rclone/fs/sync/sync.go:322 +0xb1
```

**Comment by ncw** [comment]
I've merged a fix for this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released shortly in v1.49.1
