### ISSUE TITLE
Problem with rclone panic: runtime error: slice bounds out of range 

### ISSUE THREAD

**Issue by fgendorf** [rclone/rclone#4232]
#### What is the problem you are having with rclone?
I'm trying to copy all files from my home to google drive, in that some has some mount from windows file share
#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 20.04 LTS

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy /home/ TEAMDRIVEPERU: --fast-list

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
rclone copy /home/ TEAMDRIVEPERU: -vv --fast-list
2020/05/14 13:59:17 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "copy" "/home/" "TEAMDRIVEPERU:" "-vv" "--fast-list"]
2020/05/14 13:59:17 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/05/14 13:59:20 DEBUG : mkdir.sh: Size and modification time the same (differ by -170.875µs, within tolerance 1ms)
2020/05/14 13:59:20 DEBUG : mkdir.sh: Unchanged skipping
2020/05/14 13:59:20 DEBUG : mount.sh: Size and modification time the same (differ by -804.994µs, within tolerance 1ms)
2020/05/14 13:59:20 DEBUG : mount.sh: Unchanged skipping
2020/05/14 13:59:20 DEBUG : umount.sh: Size and modification time the same (differ by -289.495µs, within tolerance 1ms)
2020/05/14 13:59:20 DEBUG : umount.sh: Unchanged skipping
2020/05/14 13:59:21 DEBUG : 02AcademicManagement/2016ProcesosAcademicosANSYS-Perú.xlsx: Size and modification time the same (differ by -498.9µs, within tolerance 1ms)
2020/05/14 13:59:21 DEBUG : 02AcademicManagement/2016ProcesosAcademicosANSYS-Perú.xlsx: Unchanged skipping
2020/05/14 13:59:21 DEBUG : 02AcademicManagement/2016ProcesosTraining-Perú.xlsx: Size and modification time the same (differ by -377.3µs, within tolerance 1ms)
2020/05/14 13:59:21 DEBUG : 02AcademicManagement/2016ProcesosTraining-Perú.xlsx: Unchanged skipping
2020/05/14 13:59:21 DEBUG : 02AcademicManagement/ANSYS_ACADEMIC_INFO.docx: Size and modification time the same (differ by -162µs, within tolerance 1ms)
2020/05/14 13:59:21 DEBUG : 02AcademicManagement/ANSYS_ACADEMIC_INFO.docx: Unchanged skipping
2020/05/14 13:59:21 DEBUG : 08InternalDocuments/09Gestion-externa (px4-300d-TIJWBR) (S) - Acceso directo.lnk: Size and modification time the same (differ by -487µs, within tolerance 1ms)
2020/05/14 13:59:21 DEBUG : 08InternalDocuments/09Gestion-externa (px4-300d-TIJWBR) (S) - Acceso directo.lnk: Unchanged skipping
2020/05/14 13:59:21 DEBUG : 08InternalDocuments/7423.docx: Size and modification time the same (differ by -30.5µs, within tolerance 1ms)
2020/05/14 13:59:21 DEBUG : 08InternalDocuments/7423.docx: Unchanged skipping
2020/05/14 13:59:21 DEBUG : 08InternalDocuments/BASE LIQUIDACION DE IMPORTACIONES ECUADOR Ansys.xls: Size and modification time the same (differ by -335.3µs, within tolerance 1ms)
2020/05/14 13:59:21 DEBUG : 08InternalDocuments/BASE LIQUIDACION DE IMPORTACIONES ECUADOR Ansys.xls: Unchanged skipping
panic: runtime error: slice bounds out of range [:4294967291] with capacity 8388608

goroutine 20 [running]:
github.com/rclone/rclone/backend/local.(*localOpenFile).Read(0xc0006e6120, 0xc00252a000, 0x800000, 0x800000, 0x7f80d0fd2818, 0xc0001a54d8, 0xd)
	/home/runner/work/rclone/src/github.com/rclone/rclone/backend/local/local.go:841 +0x52f
github.com/rclone/rclone/fs/operations.(*reOpen).Read(0xc0005d1d00, 0xc00252a000, 0x800000, 0x800000, 0x0, 0x0, 0x0)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/operations/reopen.go:103 +0xea
github.com/rclone/rclone/fs/accounting.(*Account).read(0xc000448c30, 0x7f80d11a5b78, 0xc0005d1d00, 0xc00252a000, 0x800000, 0x800000, 0xc00213bfc0, 0x7f80d115c1ff, 0xc000556080)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/accounting/accounting.go:221 +0x9a
github.com/rclone/rclone/fs/accounting.(*Account).Read(0xc000448c30, 0xc00252a000, 0x800000, 0x800000, 0x0, 0x0, 0x0)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/accounting/accounting.go:231 +0xe2
github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport.(*MediaBuffer).loadChunk(0xc00213bfc0, 0x40cbd8, 0x40)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport/buffer.go:51 +0x76
github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport.(*MediaBuffer).Chunk(0xc00213bfc0, 0xc00213bfc0, 0x800000, 0xc00252a000, 0xc0002d2650, 0xc000201fc0, 0x0)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport/buffer.go:37 +0xf8
github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport.PrepareUpload(0x19f6580, 0xc000448c30, 0x800000, 0xf, 0x19f6580, 0xc000448c30, 0x16cbf2c)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport/media.go:208 +0xbc
github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport.NewInfoFromMedia(0x19f6580, 0xc000448c30, 0xc0001a58a0, 0x1, 0x1, 0xc0002506d0)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/google.golang.org/api/internal/gensupport/media.go:237 +0x8c
github.com/rclone/rclone/vendor/google.golang.org/api/drive/v3.(*FilesCreateCall).Media(...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/google.golang.org/api/drive/v3/drive-gen.go:5940
github.com/rclone/rclone/backend/drive.(*Fs).PutUnchecked.func1(0x203000, 0x24c10e0, 0x13d0900)
	/home/runner/work/rclone/src/github.com/rclone/rclone/backend/drive/drive.go:1875 +0x19a
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0x1, 0xc001dbb860, 0x7822db, 0xc0001a5a08, 0x40cbd8)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/fs.go:1417 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc000454840, 0xc001dbb860, 0x1, 0xf, 0x40)
	/home/runner/work/rclone/src/github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x8b
github.com/rclone/rclone/lib/pacer.(*Pacer).CallNoRetry(...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/lib/pacer/pacer.go:225
github.com/rclone/rclone/backend/drive.(*Fs).PutUnchecked(0xc0004989c0, 0x1a28100, 0xc0004e2700, 0x19f6580, 0xc000448c30, 0x7f80d11a59f8, 0xc000716fc0, 0xc000658150, 0x1, 0x1, ...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/backend/drive/drive.go:1873 +0x546
github.com/rclone/rclone/backend/drive.(*Fs).Put(0xc0004989c0, 0x1a28100, 0xc0004e2700, 0x19f6580, 0xc000448c30, 0x7f80d11a59f8, 0xc000716fc0, 0xc000658150, 0x1, 0x1, ...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/backend/drive/drive.go:1819 +0x19c
github.com/rclone/rclone/fs/operations.Copy(0x1a28100, 0xc0004e2700, 0x1a3cb20, 0xc0004989c0, 0x0, 0x0, 0xc000714e80, 0x40, 0x1a3d620, 0xc000716fc0, ...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/operations/operations.go:425 +0x152c
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc0002fc8c0, 0x1a28100, 0xc0004e2700, 0xc0003f2c30, 0x1a3cb20, 0xc0004989c0, 0xc0002fc998)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/sync/sync.go:331 +0x21c
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/sync/sync.go:356 +0xb1
```

**Comment by animosity22** [comment]
Are you using any shared drives / shortcuts? 

Can you try and validate with the latest beta you get the same issue?

**Comment by fgendorf** [comment]
Hi, my OS is linux, so I'm using mount -t cifs to mount my storage appliance, my idea is migrate to google TeamDrive.
The problem apparently was solved with "cache=loose" option on cifs mount, I transferred 80GB until now (yes, the internet there has only 12Mb Upload).
I found more people with this problem when use remote share, maybe the speed of rclone read file remote are fast then cache of cifs... copy from storage to another place works, the problem only happens on rclone, but option cache=loose "solved" for me.

**Comment by ncw** [comment]
Hmm, this issue is ringing a bell...

What is happening is that the read syscall returned that it has read 4294967291 bytes = `0xfffffffb` - this is likely really an error code of `-5` which is `EIO` or IO error.

So here is what I think happened...

You are running a 64 bit system. However cifs at some point returned a 32 bit error number `-5` EIO. This got promoted to a 64 bit `0xfffffffb` and the check for it being negative and an error was missed so it was returned to rclone as the number of bytes read.

So I think this is probably a kernel bug rather than an rclone bug...

Can you reproduce it?

If so can you run

    strace -f rclone copy /home/ TEAMDRIVEPERU: --fast-list 2>&1 | tee rclone.log

This will produce **a lot** of logs. If you could gzip the log and attach it here then we will see if it is a kernel bug or a go runtime bug. Either way we can report it upstream!

Thanks

**Comment by fgendorf** [comment]
Hi, I reproduce now, do you know if there any sensitive information in it? No problem for me upload here "public"?

**Comment by fgendorf** [comment]
Looking quickly I didn't found any sensitive information, follow the log.

Thanks
[rclone.log.gz](https://github.com/rclone/rclone/files/4635145/rclone.log.gz)

**Comment by ncw** [comment]
Very helpful thank you :-)

Here are the relevant lines.

- The first shows rclone reading from file descriptor 16
- The second shows the result. You can see here that rclone provided an 8 MiB buffer but the syscall returned that it has read 4GB of data... What it meant to return was -5 EIO I think.

```
[pid 27419] read(16,  <unfinished ...>
[pid 27423] <... read resumed> "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8388608) = 4294967291
```

So I'd say that is pretty convincingly a kernel bug!

This should probably be [reported to Ubuntu](https://wiki.ubuntu.com/Kernel/Bugs) as they supply your kernel...

**Comment by ncw** [comment]
I'm going to close this one as it isn't an rclone bug.
