### ISSUE TITLE
transfer file via Windows Explorer causes weird behavior

### ISSUE THREAD

**Issue by affinityDrops** [rclone/rclone#4509]
#### What is the problem you are having with rclone?
copying or moving some files through Windows Explorer causes this error:
![image](https://user-images.githubusercontent.com/39024071/90224938-74b2a680-de4b-11ea-878a-1da95b317bc9.png)
And then rclone process terminates with error message

I have tried many things to figure out what causes it:
1. rename filename to supersimple `aaa.zip` **same error**
2. modify some bytes of random position **same error**
3. upload `aaa_copied.zip` **same error**
3. upload `aaa.zip` from `echo 'hi' > aaa.zip` **same error**

But this cases were different:
1. upload `bbb.zip` from `cat aaa.zip | bbb.zip` **no error**
1. copy via `rclone copy`

I have not tried reinstalling rclone itself.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 (64bits) Build 19041.450

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive _and_ Crypt over that Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
I used Windows Explorer

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
This is what rclone process prints after termination
```
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x402ffe]

goroutine 17 [running, locked to thread]:
runtime.throw(0x197812c, 0x5)
        runtime/panic.go:1116 +0x79 fp=0xc000337d20 sp=0xc000337cf0 pc=0x439879
runtime.sigpanic()
        runtime/signal_windows.go:249 +0x228 fp=0xc000337d50 sp=0xc000337d20 pc=0x44e9f8
indexbytebody(0x500000000000501, 0xaff, 0x443800, 0xc00006c300, 0xaff, 0x0, 0x500000000000501, 0x500000000000501, 0xaff, 0xc000337df8, ...)
        internal/bytealg/indexbyte_amd64.s:124 +0xce fp=0xc000337d58 sp=0xc000337d50 pc=0x402ffe
runtime.findnull(0x500000000000501, 0xc000337df8)
        runtime/string.go:450 +0x87 fp=0xc000337db0 sp=0xc000337d58 pc=0x453fb7
runtime.gostring(0x500000000000501, 0xc0001cb880, 0x2e74fb80)
        runtime/string.go:316 +0x36 fp=0xc000337e08 sp=0xc000337db0 pc=0x453c66
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse._Cfunc_GoString(...)
        _cgo_gotypes.go:316
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.c_GoString(...)
        github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host_cgo.go:600
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.hostRelease(0x500000000000501, 0x2e74fcb0, 0x0)
        github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host.go:272 +0x94 fp=0xc000337e68 sp=0xc000337e08 pc=0x13aa7c4
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.go_hostRelease(...)
        github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host_cgo.go:804
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse._cgoexpwrap_10a0d267ca94_go_hostRelease(0x500000000000501, 0x2e74fcb0, 0x0)
        _cgo_gotypes.go:779 +0x3c fp=0xc000337e90 sp=0xc000337e68 pc=0x13b009c
runtime.call32(0x0, 0x2e74faa0, 0x2e74fc10, 0x18)
        runtime/asm_amd64.s:539 +0x42 fp=0xc000337ec0 sp=0xc000337e90 pc=0x468b92
runtime.cgocallbackg1(0x0)
        runtime/cgocall.go:332 +0x196 fp=0xc000337f58 sp=0xc000337ec0 pc=0x404a96
runtime.cgocallbackg(0x0)
        runtime/cgocall.go:207 +0xe2 fp=0xc000337fc0 sp=0xc000337f58 pc=0x404852
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
        runtime/asm_amd64.s:793 +0xb2 fp=0xc000337fe0 sp=0xc000337fc0 pc=0x46a1f2
runtime.goexit()
        runtime/asm_amd64.s:1373 +0x1 fp=0xc000337fe8 sp=0xc000337fe0 pc=0x46a9c1

goroutine 1 [select]:
github.com/rclone/rclone/cmd/cmount.Mount(0x1d5e3e0, 0xc000194540, 0xc00003a118, 0x2, 0x1975ea8, 0x1)
        github.com/rclone/rclone/cmd/cmount/mount.go:245 +0x21c
github.com/rclone/rclone/cmd/mountlib.NewMountCommand.func1(0xc000160840, 0xc000092c80, 0x2, 0x4)
        github.com/rclone/rclone/cmd/mountlib/mount.go:349 +0x2bf
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0xc000160840, 0xc000092c40, 0x4, 0x4, 0xc000160840, 0xc000092c40)
        github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:846 +0x2a4
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x151f6a0, 0x5f363ee7, 0x2958680, 0xc000102058)
        github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:950 +0x350
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:887
github.com/rclone/rclone/cmd.Main()
        github.com/rclone/rclone/cmd/cmd.go:514 +0x99
main.main()
        github.com/rclone/rclone/rclone.go:14 +0x27

goroutine 8 [select]:
github.com/rclone/rclone/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000100f00)
        github.com/rclone/rclone/vendor/go.opencensus.io/stats/view/worker.go:154 +0x107
created by github.com/rclone/rclone/vendor/go.opencensus.io/stats/view.init.0
        github.com/rclone/rclone/vendor/go.opencensus.io/stats/view/worker.go:32 +0x5e

goroutine 43 [select]:
github.com/rclone/rclone/backend/drive.(*Fs).ChangeNotify.func1(0xc000194540, 0xc000804060, 0x1d49400, 0xc00003a128, 0xc000294350)
        github.com/rclone/rclone/backend/drive/drive.go:2655 +0x14e
created by github.com/rclone/rclone/backend/drive.(*Fs).ChangeNotify
        github.com/rclone/rclone/backend/drive/drive.go:2646 +0x6e

goroutine 23 [syscall]:
os/signal.signal_recv(0x0)
        runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        os/signal/signal_unix.go:23 +0x29
created by os/signal.Notify.func1
        os/signal/signal.go:127 +0x4b

goroutine 70 [syscall]:
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse._Cfunc_hostMount(0x14, 0xc000689d90, 0x2cbc800, 0x0)
        _cgo_gotypes.go:481 +0x54
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.c_hostMount.func1(0xc000000014, 0xc000689d90, 0x2cbc800, 0x2cbc800)
        github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host_cgo.go:701 +0x8c
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.c_hostMount(0xc000000014, 0xc000689d90, 0x2cbc800, 0xc000689d90)
        github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host_cgo.go:701 +0x44
github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.(*FileSystemHost).Mount(0xc0001cb880, 0xc00003a118, 0x2, 0xc000115040, 0x11, 0x14, 0x0)
        github.com/rclone/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host.go:666 +0x3ff
github.com/rclone/rclone/cmd/cmount.mount.func1(0xc0001cb880, 0xc00003a118, 0x2, 0xc000115040, 0x11, 0x14, 0x1d5e3e0, 0xc000194540, 0xc000095b00)
        github.com/rclone/rclone/cmd/cmount/mount.go:168 +0x74
created by github.com/rclone/rclone/cmd/cmount.mount
        github.com/rclone/rclone/cmd/cmount/mount.go:166 +0x3da

goroutine 67 [IO wait]:
internal/poll.runtime_pollWait(0x29e26d18, 0x72, 0x1d1dde0)
        runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc0004d1848, 0x72, 0x1498600, 0x0, 0x0)
        internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x2951b10, 0xc0004d1698, 0x1a21e50, 0xf5571565a1b4d98f, 0xe5ec6f4f1e16b2f9, 0xf5571565a1b4d98f)
        internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc0004d1680, 0xc000722000, 0xf62, 0xf62, 0x0, 0x0, 0x0)
        internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc0004d1680, 0xc000722000, 0xf62, 0xf62, 0xf2a50866761a3f6b, 0xd9cd547ac52f78cf, 0xecf8a802181c06f8)
        net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc000208018, 0xc000722000, 0xf62, 0xf62, 0x0, 0x0, 0x0)
        net/net.go:184 +0x95
github.com/rclone/rclone/fs/fshttp.(*timeoutConn).readOrWrite(0xc0001c24c0, 0xc00032d830, 0xc000722000, 0xf62, 0xf62, 0x1cdf27b, 0xc00032d8c0, 0x40e550)
        github.com/rclone/rclone/fs/fshttp/http.go:75 +0x4f
github.com/rclone/rclone/fs/fshttp.(*timeoutConn).Read(0xc0001c24c0, 0xc000722000, 0xf62, 0xf62, 0x30000, 0x40e550, 0x10)
        github.com/rclone/rclone/fs/fshttp/http.go:87 +0x91
crypto/tls.(*atLeastReader).Read(0xc0005210a0, 0xc000722000, 0xf62, 0xf62, 0x28, 0x20, 0xc00032d918)
        crypto/tls/conn.go:760 +0x67
bytes.(*Buffer).ReadFrom(0xc00078de58, 0x1d17500, 0xc0005210a0, 0x40c25c, 0x171f500, 0x1877a40)
        bytes/buffer.go:204 +0xb8
crypto/tls.(*Conn).readFromUntil(0xc00078dc00, 0x2c3f0008, 0xc0001c24c0, 0x5, 0xc0001c24c0, 0xc000098140)
        crypto/tls/conn.go:782 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00078dc00, 0x0, 0x0, 0x0)
        crypto/tls/conn.go:589 +0x11c
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00078dc00, 0xc00012c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        crypto/tls/conn.go:1233 +0x162
net/http.(*persistConn).Read(0xc000300000, 0xc00012c000, 0x1000, 0x1000, 0xc000804000, 0xc00032dc70, 0x4066b5)
        net/http/transport.go:1825 +0x7c
bufio.(*Reader).fill(0xc000095680)
        bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc000095680, 0x1, 0x0, 0x0, 0x1, 0xc0005cc000, 0x0)
        bufio/bufio.go:138 +0x56
net/http.(*persistConn).readLoop(0xc000300000)
        net/http/transport.go:1978 +0x1af
created by net/http.(*Transport).dialConn
        net/http/transport.go:1647 +0xc5d

goroutine 68 [select]:
net/http.(*persistConn).writeLoop(0xc000300000)
        net/http/transport.go:2277 +0x123
created by net/http.(*Transport).dialConn
        net/http/transport.go:1648 +0xc82

goroutine 69 [select]:
github.com/rclone/rclone/vfs/vfscache.(*Cache).cleaner(0xc000025950, 0x1d493c0, 0xc0001cb400)
        github.com/rclone/rclone/vfs/vfscache/vfscache.go:545 +0x150
created by github.com/rclone/rclone/vfs/vfscache.New
        github.com/rclone/rclone/vfs/vfscache/vfscache.go:76 +0x374

goroutine 24 [chan receive]:
github.com/rclone/rclone/lib/atexit.Register.func1.1()
        github.com/rclone/rclone/lib/atexit/atexit.go:39 +0x4a
created by github.com/rclone/rclone/lib/atexit.Register.func1
        github.com/rclone/rclone/lib/atexit/atexit.go:38 +0x9b
```

**Comment by darthShadow** [comment]
Please specify the mount command too.

**Comment by affinityDrops** [comment]
I used `.\rclone.exe mount --vfs-cache-mode writes`

**Comment by darthShadow** [comment]
Can you please also add the debug logs from the mount?

**Comment by affinityDrops** [comment]
How do I get those?

**Comment by ncw** [comment]
Hmm, this maybe looks like a bug in cgofuse.

Can you try with [the latest beta](https://beta.rclone.org) please with the latest WinFSP and see if you can reproduce there please?
