### ISSUE TITLE
Jottacloud rclone copy using server-side copy crashed with SEGV.

### ISSUE THREAD

**Issue by gerph** [rclone/rclone#4655]
#### What is the problem you are having with rclone?

It crashed whilst performing a server side copy of a directory - it had been running for over an hour when it happened. I was running two of these copies (different destination directories) at the same time on the same machine, and both of them seemed to crash at about the same time, so I'm going to guess that they got back an unexpected response which caused that (the machine itself isn't low on memory and shouldn't have otherwise failed).

#### What is your rclone version (output from `rclone version`)

```
charles@laputa ~> rclone version
rclone v1.54.0-beta.4793.2b7994e73
- os/arch: darwin/amd64
- go version: go1.15.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

MacOS 10.14.6

####  Which cloud storage system are you using? (eg Google Drive)

Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -v copy jottacloud-crypt:archives/2020-10/home/ jottacloud-crypt:archives/2020-09/home/`

and

`rclone -v copy --transfers 40 jottacloud-crypt:archives/2020-10/home/ jottacloud-crypt:archives/2020-01/home/`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I don't have a -vv log; but I do have the surrounding logs from two processes that failed with -v selected:

```
2020/10/05 18:08:30 INFO  : charles/.cpanm/work/1584570345.8175/Perl-Critic-1.126/blib/lib/Perl/Critic/Policy/ControlStructures/ProhibitUnreachableCode.pm: Copied (server side copy)
2020/10/05 18:08:31 INFO  : charles/.cpanm/work/1584572480.1242/PPI-1.220/blib/lib/PPI/Token/Prototype.pm: Copied (server side copy)
2020/10/05 18:08:33 INFO  : charles/.cpanm/work/1584570345.8175/Perl-Critic-1.126/lib/Perl/Critic/Exception/Configuration/Option/Global/ExtraParameter.pm: Copied (server side copy)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4aac33e]

goroutine 112 [running]:
github.com/rclone/rclone/backend/jottacloud.(*Fs).copyOrMove.func1(0xc000116838, 0x8, 0x203000)
	github.com/rclone/rclone/backend/jottacloud/jottacloud.go:1091 +0x11e
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0xa, 0xc00133a6c0, 0xc00133a6c0, 0x349e6bb8, 0x11d)
	github.com/rclone/rclone/fs/fs.go:1477 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc00013a5a0, 0xc00133a6c0, 0xa, 0x40, 0x55d2ec0)
	github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x90
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0xc00013a5a0, 0xc00133a6c0, 0x56bae22, 0x2)
	github.com/rclone/rclone/lib/pacer/pacer.go:216 +0x6a
github.com/rclone/rclone/backend/jottacloud.(*Fs).copyOrMove(0xc0000ad600, 0x59ac9c0, 0xc00020c7c0, 0x56bae22, 0x2, 0xc0010267e0, 0x11d, 0xc001230000, 0xa0, 0xa0, ...)
	github.com/rclone/rclone/backend/jottacloud/jottacloud.go:1088 +0x428
github.com/rclone/rclone/backend/jottacloud.(*Fs).Copy(0xc0000ad600, 0x59ac9c0, 0xc00020c7c0, 0x59c3560, 0xc0011314a0, 0xc001230000, 0xa0, 0x5, 0x4, 0x40, ...)
	github.com/rclone/rclone/backend/jottacloud/jottacloud.go:1119 +0x1d0
github.com/rclone/rclone/backend/crypt.(*Fs).Copy(0xc0018deb40, 0x59ac9c0, 0xc00020c7c0, 0x592322be0, 0xc0013d6d20, 0xc000838ec0, 0x3d, 0xbfd6f222222c9f333, 0x3233254041111, 0x642c552, ...)
	github.com/rclone/rclone/backend/crypt/crypt.go:465 +0x115
github.com/rclone/rclone/fs/operations.Copy(0x59ac9c0, 0xc00020c7c0, 0x59c2b60, 0xc0018deb40, 0x0, 0x0, 0xc00023338ec0, 0x3d, 0x52242be0, 0xc00334420, ...)
	github.com/rclone/rclone/fs/operations/operations.go:382 +0x19a3
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00000c1e0, 0x59ac9c0, 0xc00020c7c0, 0xc0018e81e0, 0x59c2b60, 0xc0018deb40, 0x32, 0xc00000c2d0)
	github.com/rclone/rclone/fs/sync/sync.go:384 +0x22c
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
	github.com/rclone/rclone/fs/sync/sync.go:411 +0xd2
```

and

```
2020/10/05 18:12:20 INFO  : charles/ansible.gerph.old/roles/chartdirector-python/tasks/main.yaml: Copied (server side copy)
2020/10/05 18:12:21 INFO  : charles/ansible.gerph.old/roles/chartdirector-php/templates/htaccess.j2: Copied (server side copy)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4aac33e]

goroutine 148 [running]:
github.com/rclone/rclone/backend/jottacloud.(*Fs).copyOrMove.func1(0xc0001ab258, 0xc000683500, 0xc000683588)
	github.com/rclone/rclone/backend/jottacloud/jottacloud.go:1091 +0x11e
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0xa, 0xc000b9a3c0, 0xc000b9a3c0, 0x1375ef90, 0x138)
	github.com/rclone/rclone/fs/fs.go:1477 +0x3c
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc00007c540, 0xc000b9a3c0, 0xa, 0x40, 0x55d2ec0)
	github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x90
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0xc00007c540, 0xc000b9a3c0, 0x56bae22, 0x2)
	github.com/rclone/rclone/lib/pacer/pacer.go:216 +0x6a
github.com/rclone/rclone/backend/jottacloud.(*Fs).copyOrMove(0xc000604160, 0x59ac9c0, 0xc00048a000, 0x56bae22, 0x2, 0xc000b06500, 0x138, 0xc0003f6000, 0xbb, 0xbb, ...)
	github.com/rclone/rclone/backend/jottacloud/jottacloud.go:1088 +0x428
github.com/rclone/rclone/backend/jottacloud.(*Fs).Copy(0xc000604160, 0x59ac9c0, 0xc00048a000, 0x59c3560, 0xc0005ce480, 0xc0003f6000, 0xbb, 0x6, 0x5, 0x50, ...)
	github.com/rclone/rclone/backend/jottacloud/jottacloud.go:1119 +0x1d0
github.com/rclone/rclone/backend/crypt.(*Fs).Copy(0xc0003c2000, 0x59ac9c0, 0xc00048a000, 0x59c3352, 0xc000780620, 0xc000c64100, 0x38, 0xbfd62222fab53333, 0x5117b2222db, 0x6424422, ...)
	github.com/rclone/rclone/backend/crypt/crypt.go:465 +0x115
github.com/rclone/rclone/fs/operations.Copy(0x59ac9c0, 0xc00048a000, 0x59c2b60, 0xc0003c2000, 0x0, 0x0, 0xc000c64100, 0x38, 0x59c2be0, 0xc000780620, ...)
	github.com/rclone/rclone/fs/operations/operations.go:382 +0x19a3
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00000c1e0, 0x59ac9c0, 0xc00048a000, 0xc00018ef50, 0x59c2b60, 0xc0003c2000, 0x34, 0xc00000c2d0)
	github.com/rclone/rclone/fs/sync/sync.go:384 +0x22c
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
	github.com/rclone/rclone/fs/sync/sync.go:411 +0xd2
```

I guess those times aren't exactly the same times, but it had been working just fine, and they failed quite close together.

**Comment by buengese** [comment]
Thanks there was rather obvious mistake in the DirMove workaround where the response of the http request was used without checking the error first. This workaround isn't required anymore anyways so I've removed it.
