### ISSUE TITLE
Rclone hangs during restic backups to FTP backend with concurrency set

### ISSUE THREAD

**Issue by iridescent86** [rclone/rclone#4694]
#### What is the problem you are having with rclone?

When limiting the amount of concurrent connection to a FTP server (using the concurrency configuration knob), we are experiencing hangs when performing backups using restic.
Limiting the number of connections that restic establishes to rclone (by adding '-o rclone.connections=N', with N being the same value than the one chosen for concurrency) provides a workaround.
Please take a look at https://github.com/restic/restic/issues/2925 where the issue is further discussed.

#### What is your rclone version (output from `rclone version`)

reproduced with both the following version (latest prod and beta at the time i'm writing this):
rclone v1.53.1 - os/arch: linux/amd64 - go version: go1.15
rclone v1.54.0-beta.4831.4e2b5389d - os/arch: linux/amd64 - go version: go1.15.2

using the following version of restic:
restic 0.10.0 compiled with go1.15.2 on linux/amd64

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS Linux release 7.8.2003 (Core) on x86_64
kernel 3.10.0-1127.19.1.el7.x86_64

####  Which cloud storage system are you using? (eg Google Drive)

FTP server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

local-ftp repository is configured with concurrency=2
running on a system with at least 3 (V)CPU (otherwise the issue does not happen)

issue is reproduced when doing:
```
$ restic -r rclone:local-ftp:/home/upload/backup --verbose=3 backup /mnt/snapshot
```

issue is NOT reproduced when doing (limiting the number of rclone connection to the same value than concurrency):
```
$ RESTIC_PASSWORD=password restic -r rclone:local-ftp:/home/upload/backup -o rclone.connections=2 backup /mnt/snapshot
```

issue is NOT reproduced when doing (using TCP sockets instead of stdio):
```
$ rclone serve restic --addr 127.0.0.1:8080 --b2-hard-delete --drive-use-trash=false local-ftp:/home/upload/backup &
$ restic -r rest:http://127.0.0.1:8080 backup /mnt/snapshot
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Issue never appears when using rclone directly.
When -vv is added to the restic command it does not seem to be propagated to rclone.
However, the following trace could be captured when sending SIGABRT to rclone once it locked up.

```
rclone: goroutine 49211 [chan receive]:
rclone: github.com/rclone/rclone/lib/pacer.(*TokenDispenser).Get(...)
rclone: 	github.com/rclone/rclone/lib/pacer/tokens.go:24
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).getFtpConnection(0xc0004902d0, 0xc, 0xc000adb7ba, 0x2)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:245 +0x1e5
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).getInfo(0xc0004902d0, 0xc000adb7b0, 0xc, 0xc, 0xa, 0xc000040870)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:606 +0xa7
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).mkdir(0xc0004902d0, 0xc000adb7b0, 0xc, 0xc000adb7b0, 0xc)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:638 +0xb0
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).mkParentDir(0xc0004902d0, 0xc000040870, 0x48, 0xc000b23740, 0xc000068c70)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:674 +0xb3
rclone: github.com/rclone/rclone/backend/ftp.(*Fs).Put(0xc0004902d0, 0x59a79a0, 0xc000c14dc0, 0x596e620, 0xc000988d20, 0x59b7f00, 0xc000ba6640, 0x0, 0x0, 0x0, ...)
rclone: 	github.com/rclone/rclone/backend/ftp/ftp.go:583 +0x4c
rclone: github.com/rclone/rclone/fs/operations.RcatSize(0x59a79a0, 0xc000c14dc0, 0x59be060, 0xc0004902d0, 0xc000040870, 0x48, 0x5984c20, 0xc00047e0f0, 0x4eb96c, 0xbfdaf5925bbc5780, ...)
rclone: 	github.com/rclone/rclone/fs/operations/operations.go:1428 +0x339
rclone: github.com/rclone/rclone/cmd/serve/restic.(*Server).postObject(0xc0001b83e0, 0x599b7e0, 0xc00055c210, 0xc000bcd200, 0xc000040870, 0x48)
rclone: 	github.com/rclone/rclone/cmd/serve/restic/restic.go:275 +0x170
rclone: github.com/rclone/rclone/cmd/serve/restic.(*Server).ServeHTTP(0xc0001b83e0, 0x599b7e0, 0xc00055c210, 0xc000bcd200)
rclone: 	github.com/rclone/rclone/cmd/serve/restic/restic.go:242 +0x759
rclone: golang.org/x/net/http2.(*serverConn).runHandler(0xc000259500, 0xc00055c210, 0xc000bcd200, 0xc000895ea0)
rclone: 	golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/server.go:2147 +0x8b
rclone: created by golang.org/x/net/http2.(*serverConn).processHeaders
rclone: 	golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/server.go:1881 +0x505
```

**Comment by ncw** [comment]
The `--ftp-concurrency` flag has caused quite a few deadlocks in the past.

Unfortunately if you set that flag then ask for more than that many connections then rclone will pause until one of the connections is released.

I don't think that there is anything rclone can do here.

However

> Limiting the number of connections that restic establishes to rclone (by adding '-o rclone.connections=N', with N being the same value than the one chosen for concurrency) provides a workaround.

Seems to be the correct solution.

Can you think of a different solution?

**Comment by iridescent86** [comment]
Thanks for your feedback on this. Aligning rclone.connections to the same value than ftp-concurrency appears to be the best solution so far, another one was to use TCP sockets instead of stdio in which case the deadlock does not occur for a reason i don't know.

It works well once you know it, i think that the main issue there is that users will often not know about that setting. Could there be a way for restic to discover the ftp-concurrency value configured at the rclone level so it could cap its rclone.connections to the same value?

**Comment by ncw** [comment]
> Thanks for your feedback on this. Aligning rclone.connections to the same value than ftp-concurrency appears to be the best solution so far,

Great

> another one was to use TCP sockets instead of stdio in which case the deadlock does not occur for a reason i don't know.

Maybe it didn't use as much concurrency for some reason

> It works well once you know it, i think that the main issue there is that users will often not know about that setting. Could there be a way for restic to discover the ftp-concurrency value configured at the rclone level so it could cap its rclone.connections to the same value?

I can't think of an easy way for restic to discover the concurrency value - it would mean extending the REST API I think.

Maybe rclone could warn in the log that ftp concurrency is too low for the current usage.  Maybe if it had been waiting for an ftp connection for more than 60s it could print an warning

    WARNING: waited 60s for an ftp connection - ftp concurrency may be too low

would that have helped?
