### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CyberPoison** [rclone/rclone#5540]
Hi i have some issues when trying to mount my Google Drive Storage with cache + encrypt 

#### What is the problem you are having with rclone?
```
2021/08/17 09:17:47 NOTICE: WARNING: Cache backend is deprecated and may be removed in future. Please use VFS instead.
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17ead91]

goroutine 23 [running]:
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1.1()
        github.com/rclone/rclone/cmd/mountlib/mount.go:256 +0x51
sync.(*Once).doSlow(0xc00069c4b0, 0xc000063e38)
        sync/once.go:68 +0xec
sync.(*Once).Do(...)
        sync/once.go:59
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Wait.func1()
        github.com/rclone/rclone/cmd/mountlib/mount.go:254 +0x65
github.com/rclone/rclone/lib/atexit.Run.func1()
        github.com/rclone/rclone/lib/atexit/atexit.go:104 +0x7f
sync.(*Once).doSlow(0x2e05c98, 0x1f1f140)
        sync/once.go:68 +0xec
sync.(*Once).Do(...)
        sync/once.go:59
github.com/rclone/rclone/lib/atexit.Run()
        github.com/rclone/rclone/lib/atexit/atexit.go:102 +0xb6
github.com/rclone/rclone/lib/atexit.Register.func1.1()
        github.com/rclone/rclone/lib/atexit/atexit.go:52 +0xea
created by github.com/rclone/rclone/lib/atexit.Register.func1
        github.com/rclone/rclone/lib/atexit/atexit.go:44 +0x94
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.56.0
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-153-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.5
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 18.04

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone mount --daemon --allow-other --dir-cache-time 24h --vfs-read-chunk-size 124M --vfs-read-chunk-size-limit 4G --buffer-size 512M --vfs-cache-mode writes Cloud\ Storage\ Server\ 1\ Uncrypt:/ /mnt/Cloud\ Storage/Cloud\ Storage\ Server\ 1/

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
rclone mount --daemon --allow-other --dir-cache-time 24h --vfs-read-chunk-size 124M --vfs-read-chunk-size-limit 4G --buffer-size 512M --vfs-cache-mode writes -vv Cloud\ Storage\ Server\ 1\ Uncrypt:/ /mnt/Cloud\ Storage/Cloud\ Storage\ Server\ 1/
2021/08/17 09:23:40 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "mount" "--daemon" "--allow-other" "--dir-cache-time" "24h" "--vfs-read-chunk-size" "124M" "--vfs-read-chunk-size-limit" "4G" "--buffer-size" "512M" "--vfs-cache-mode" "writes" "-vv" "Cloud Storage Server 1 Uncrypt:/" "/mnt/Cloud Storage/Cloud Storage Server 1/"]
2021/08/17 09:23:40 DEBUG : Creating backend with remote "Cloud Storage Server 1 Uncrypt:/"
2021/08/17 09:23:40 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/08/17 09:23:40 DEBUG : Creating backend with remote "Cache Cloud Storage 1:/"
2021/08/17 09:23:40 NOTICE: WARNING: Cache backend is deprecated and may be removed in future. Please use VFS instead.
2021/08/17 09:23:40 DEBUG : Creating backend with remote "Cloud Storage 1:/"
2021/08/17 09:23:40 DEBUG : fs cache: renaming cache item "Cloud Storage 1:/" to be canonical "Cloud Storage 1:"
2021/08/17 09:23:40 DEBUG : Cache Cloud Storage 1: wrapped Cloud Storage 1: at root
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Cache DB path: /root/.cache/rclone/cache-backend/Cache Cloud Storage 1.db
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Cache chunk path: /root/.cache/rclone/cache-backend/Cache Cloud Storage 1
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Chunk Memory: true
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Chunk Size: 32Mi
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Chunk Total Size: 64Gi
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Chunk Clean Interval: 1m0s
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: Workers: 4
2021/08/17 09:23:40 INFO  : Cache Cloud Storage 1: File Age: 1d
2021/08/17 09:23:40 DEBUG : fs cache: renaming cache item "Cache Cloud Storage 1:/" to be canonical "Cache Cloud Storage 1:"
2021/08/17 09:23:40 DEBUG : fs cache: switching user supplied name "Cache Cloud Storage 1:/" for canonical name "Cache Cloud Storage 1:"
2021/08/17 09:23:40 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2021/08/17 09:23:40 DEBUG : pacer: Rate limited, increasing sleep to 1.245654787s
2021/08/17 09:23:40 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2021/08/17 09:23:40 DEBUG : pacer: Rate limited, increasing sleep to 2.143330497s
2021/08/17 09:23:42 DEBUG : pacer: Reducing sleep to 0s
2021/08/17 09:24:40 DEBUG : Cache remote Cache Cloud Storage 1:: starting cleanup
2021/08/17 09:24:42 DEBUG : Google drive root '': Checking for changes on remote
```

**Comment by ncw** [comment]
Can you replicate this crash?

If so how do you make it happen?

Can you post a complete log which includes rclone startup and the crash please? There isn't quite enough context in the crash report - rclone appears to be exiting but why?

Thanks

**Comment by CyberPoison** [comment]
Hi, thanks for your reply, I have this issue when i do control+c to exit since the --daemon looks like don't working as expected, i will edit my issue report with more details if possible of course.
Can you tell me how i can add more details? Wich command to run etc..?

**Comment by ncw** [comment]
Oh, I think this is fixed already.

Try a release from here

https://beta.rclone.org/branch/v1.56-stable/v1.56.0-beta.5606.03bcf81c5.v1.56-stable/

This is a preview of 1.56.1

**Comment by CyberPoison** [comment]
when trying to get beta rclone installed from bach script i get a http/2 issue 
curl: (92) HTTP/2 stream 1 was closed cleanly, but before getting  all response header fields, teated as error

did you know that ?

**Comment by ncw** [comment]
Try again - the beta server ran out of disk space for a while!

**Comment by wes1993** [comment]
Hello,
I have the same problem, do you know when this will be added to the stable release?

**Comment by ncw** [comment]
The fix is queued for 1.56.1 - does https://beta.rclone.org/branch/v1.56-stable/v1.56.0-beta.5607.b26308c42.v1.56-stable/ work for you @wes1993 ?

**Comment by wes1993** [comment]
Thanks a lot for your reply.
Yes works like a charm :)

**Comment by ivandeex** [comment]
fixed
