### ISSUE TITLE
Some rclone writes aren't being uploaded to pcloud

### ISSUE THREAD

**Issue by Yann-J** [rclone/rclone#5581]
First of all, huge hats off with Rclone, I've discovered it recently and works really well, in particular the docker volume plugin is amazing, as it pretty much makes any application compatible with any cloud provider!

#### What is the problem you are having with rclone?

File writes to a ~10Mb file mounted in a container as a docker volume through the Docker plugin (using `vfs-mode=full`) do not seem to be properly uploaded. The write is visible locally, but not in the pCloud UI even after 30 min. This is the case for both file content writes or simple `touch` operations.

New files created in the container, even copies of the original file, are uploaded fine almost immediately. Writes to smaller files also seem to be OK. It only seems to be updates to relatively large files.

I've tried flushing the VFS cache by running `sudo runc --root /run/docker/runtime-runc/plugins.moby exec $PLUGID kill -SIGHUP 1`, with no visible change.

I have found that a workaround of renaming the file, then copying it back to its original name (hence considering it a new file) works, i.e. I can see both the renamed file (but with the old content) and the new file (with the updated content) in the pCloud UI.

#### What is your rclone version (output from `rclone version`)

Latest Docker volume plugin:

```
ubuntu@ns377587:~/mediacenter/docker-compose$ sudo runc --root /run/docker/runtime-runc/plugins.moby exec $PLUGID rclone version
rclone v1.56.0-beta.5599.ae3fba2a0.retry-docker-plugin-push
- os/version: alpine 3.14.0 (64 bit)
- os/kernel: 5.11.0-31-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.6
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 64

#### Which cloud storage system are you using? (e.g. Google Drive)

pCloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Writes to a Docker volume managed by `rclone serve`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

No recent logs visible in `journalctl --unit docker`

* File update in the container (in UTC time zone)

```
root@bfdf9204a1b8:/# stat /cloud/Books/metadata.db
  File: /cloud/Books/metadata.db
  Size: 10637312  	Blocks: 20776      IO Block: 4096   regular file
Device: 4ch/76d	Inode: 4721833615467147647  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-07 06:52:04.000000000 +0000
Modify: 2021-09-07 06:52:04.000000000 +0000
Change: 2021-09-07 06:52:04.000000000 +0000
 Birth: -
```

* File details in pCloud (local time zone UTC+0200):

![image](https://user-images.githubusercontent.com/59641363/132302845-7f3b72ce-6863-4487-8bcf-d0a601cf3ddb.png)

* `rcloud.conf`:

```
[pcloud]
type = pcloud
token = {"access_token":"xxxx","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
hostname = eapi.pcloud.com
```

* Docker volume details:

```
ubuntu@ns377587:~/mediacenter/docker-compose$ docker volume inspect cloud_media
[
    {
        "CreatedAt": "2021-08-31T06:54:05Z",
        "Driver": "rclone:latest",
        "Labels": {},
        "Mountpoint": "/mnt/cloud_media",
        "Name": "cloud_media",
        "Options": {
            "remote": "pcloud:Media",
            "vfs-cache-mode": "full"
        },
        "Scope": "local",
        "Status": {
            "Mounts": [
                "2fd39261f1a25d6a2afa90c50649401c85b3435daf13c023c93b0d3edf411894",
                "42738b2d73db0973bbf971679c992be10279cfd83032b7d4886b87af8b2846e8",
                "642bc89de77e94a56570aadb33e9ca53dbc639a4a8e4874ebae16f12622cb3bd",
                "8a8ece5d351fd2496969422d1148d13084225434f30238e8a0f4311a4205d086",
                "8cde755cc0faa0738c20e183b1b6873d151062b565de51f077c452d74a67fe41",
                "aa36dac0b1a74e04027d3a1e4e726f7e4b21525bb1975801e81845f9e21e6940",
                "f0bc0772cbe50136ffbfa847fb6bba650b4e0744d36f1538fbacd1195025ffe7"
            ]
        }
    }
]
```

**Comment by ivandeex** [comment]
try this:
stop your container (and any containers that use-lock the plugin)
```
docker volume disable rclone
docker volume set rclone args="-vv --vfs-cache-mode=minimal"
docker volume enable rclone
```
start your container
journalctl docker

**Comment by ivandeex** [comment]
as volume plugin is basically a vfs mount controlled by docker daemon, you can try if playing with vfs flags can help
https://rclone.org/commands/rclone_mount/#vfs-directory-cache

**Comment by Yann-J** [comment]
Thanks, indeed lowering the caching level seems to help, and so far no strong adverse performance effect.

I'll keep playing a bit and report back, but so far it seems better.

**Comment by ivandeex** [comment]
It looks like a bug in the VFS caching layer, triggered by something in the pcloud client.
Could you do us a favor and help isolate the bug?
Basically you could enable debugging `-vv`, return the full caching like this:
```
docker volume disable rclone
docker volume set rclone args="-vv"
docker volume enable rclone
docker volume create  cloud_media -o remote=pcloud:Media,vfs-cache-mode=full
docker run --rm -it -w /cloud -v cloud_media:/cloud ubuntu:latest bash
> touch /cloud/Books/metadata.db
> stat /cloud/Books/metadata.db
> exit
journalctl docker > docker.log
```
and see what's up with the file in question :-)

**Comment by ivandeex** [comment]
It looks like a bug in the VFS caching layer, triggered by something in the pcloud client.
Could you do us a favor and help isolate the bug?

Basically you could enable debugging `-vv`:
```
docker plugin disable rclone
docker plugin set rclone args="-vv"
docker plugin enable rclone
```

return the full caching like this:
```
docker volume rm cloud_media
docker volume create cloud_media -o remote=pcloud:Media,vfs-cache-mode=full
```

see what's up with the file in question:
```
docker run -it -w /cloud -v cloud_media:/cloud ubuntu:latest bash
> touch /cloud/Books/metadata.db
> stat /cloud/Books/metadata.db
> exit
journalctl docker > docker.log
```
and attach the log here as soon as the problem reproduces
:-)

**Comment by Yann-J** [comment]
Thanks, I'll do that! Quick question, can I do this on a separate volume? I have quite a bunch of containers so updating volumes is always a bit tedious... If the plugin has `vfs-cache-mode=minimal` but I create a new separate volume just for these tests with `vfs-cache-mode=full`, will it be enough?

**Comment by ivandeex** [comment]
> Thanks, I'll do that! Quick question, can I do this on a separate volume? I have quite a bunch of containers so updating volumes is always a bit tedious...

Holy true :-)

> If the plugin has `vfs-cache-mode=minimal` but I create a new separate volume just for these tests with `vfs-cache-mode=full`, will it be enough?

Yes. Plugin options like `-vfs-xxx` are just defaults for volume create options.
Except for debugging `-vv` which is a plugin-level option :(

**Comment by Yann-J** [comment]
Hmm ok, I have reproduced with the verbose logs as follows:

* Created 2 different volumes with different cache modes  - but pointing to the same pcloud location
* 1 container with VFS cache mode `full` (`docker volume create cloud_media_test -d rclone -o remote=pcloud:Media -o vfs-cache-mode=full`)
* 1 container with VFS cache mode `minimal`
* Made a first write from the `full` container, was correctly propagated to the `minimal` container pretty rapidly
* Made a second write from the `minimal` container, never got uploaded to pcloud

So, oddly, it's the non-cached volume that was acting up this time...

I wasn't sure if simple timestamp updates would be enough to test for file changes to be picked up so I made binary updates (removing from a Calibre sqlite3 books database).

## Container 1 (`full`)

```
$ stat /cloud/Books/metadata.db
  File: /cloud/Books/metadata.db
  Size: 10616832  	Blocks: 20736      IO Block: 4096   regular file
Device: 10002ah/1048618d	Inode: 4721833615467147647  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-08 06:09:32.000000000 +0000
Modify: 2021-09-08 06:09:32.000000000 +0000
Change: 2021-09-08 06:09:32.000000000 +0000

# Make an update (remove a book from the calibre sqlite db)
$ /app/calibre/calibredb --with-library=/cloud/Books/ remove 714

# New timestamp
$ stat /cloud/Books/metadata.db
  File: /cloud/Books/metadata.db
  Size: 10616832  	Blocks: 20736      IO Block: 4096   regular file
Device: 10002ah/1048618d	Inode: 4721833615467147647  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-08 20:11:52.000000000 +0000
Modify: 2021-09-08 20:11:52.000000000 +0000
Change: 2021-09-08 20:11:52.000000000 +0000
```

## Container 2 (`minimal`)

```
# Correct timestamp
$ stat /cloud/Books/metadata.db
  File: /cloud/Books/metadata.db
  Size: 10616832  	Blocks: 20736      IO Block: 4096   regular file
Device: 5eh/94d	Inode: 4721833615467147647  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-08 20:11:52.000000000 +0000
Modify: 2021-09-08 20:11:52.000000000 +0000
Change: 2021-09-08 20:11:52.000000000 +0000

# Check that update is reflected (book not present)
$ /app/calibre/calibredb --with-library=/cloud/Books/ show_metadata 714
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/db/cli/main.py", line 251, in main
  File "calibre/db/cli/main.py", line 41, in run_cmd
  File "calibre/db/cli/cmd_show_metadata.py", line 49, in main
TypeError: %d format: a number is required, not builtin_function_or_method

# Make another update
$ /app/calibre/calibredb --with-library=/cloud/Books/ remove 710

# New timestamps
$ stat /cloud/Books/metadata.db
  File: /cloud/Books/metadata.db
  Size: 10616832  	Blocks: 20736      IO Block: 4096   regular file
Device: 5eh/94d	Inode: 4721833615467147647  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-08 20:19:26.000000000 +0000
Modify: 2021-09-08 20:19:26.000000000 +0000
Change: 2021-09-08 20:19:26.000000000 +0000
```

That last update was never seen by the first container, nor the pcloud UI.

The logs are quite huge (unfortunately I still had some other containers running rclone volumes at the same time, which polluted the logs) - I've stripped the docker daemon verbosity to keep only the plugin logs for readability... Nothing seems out of the ordinary as far as I can tell around the 20:19 timestamp...

[docker.log.zip](https://github.com/rclone/rclone/files/7131790/docker.log.zip)

Thanks for the help!

**Comment by ncw** [comment]
Is it possible to reproduce this on a plain `rclone mount` without involving docker?

**Comment by Yann-J** [comment]
Yes I can certainly try, I think this should be easy to do.

I suspect that the issue is specific to pcloud, as it seems to happen whenever there's a potential for conflicts - i.e. 2 parallel updates made from 2 machines, which causes a version conflict that then causes pcloud to refuse to process updates from a conflicted file...

Of course I wouldn't expect rclone to resolve version conflicts... that is pcloud's job... However, I imagine there's a way for rclone to have some logic to mirror whatever's on pcloud, overwriting local updates. I know Nextcloud saves a copy of the local file under a different name whenever that happens, but the original file name always mirrors the "winning" server version.

Does this make sense?

**Comment by ncw** [comment]
> Yes I can certainly try, I think this should be easy to do.
> 
> I suspect that the issue is specific to pcloud, as it seems to happen whenever there's a potential for conflicts - i.e. 2 parallel updates made from 2 machines, which causes a version conflict that then causes pcloud to refuse to process updates from a conflicted file...

Ah... interesting... `rclone mount` doesn't guarantee anything in particular if you use it from two places at once.

> Of course I wouldn't expect rclone to resolve version conflicts... that is pcloud's job... However, I imagine there's a way for rclone to have some logic to mirror whatever's on pcloud, overwriting local updates. I know Nextcloud saves a copy of the local file under a different name whenever that happens, but the original file name always mirrors the "winning" server version.
> 
> Does this make sense?

I think so. Can we find out what pcloud does?

**Comment by Yann-J** [comment]
OK, I managed to reproduce locally with a bare-bones setup, just rclone mount, no docker, and no file conflicts.

Here's how it goes:

```
# I already have my /Media/Books/ pcloud folder mounted with the official pcloud client (Mac) at ~/Books/

# mount pcloud remote with rclone
$ rclone mount pcloud:/ ~/pcloud/ --vfs-cache-mode=minimal -vv 2>&1 | tee rclone.logs

# So now these are pointing to the same remote folder:
# ~/Books/ ==> pcloud official client
# ~/pcloud/Media/Books/ ==> rclone

# Check all write timestamps are the same initially
 $ stat ~/pcloud/Media/Books/metadata.db
889192459 4 -rw-r--r-- 1 yann staff 0 10625024 "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" 4096 20752 0 /Users/yann/pcloud/Media/Books/metadata.db
$ stat ~/Books/metadata.db
905969670 1240 -rw-r--r-- 1 yann staff 0 10625024 "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" "Sep 11 14:20:04 2021" 4096 20752 0 /Users/yann/pCloud Drive/Media/Books/metadata.db

# Check a random book - present in both places
$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/Books/ show_metadata 48
Title               : Dexter in the Dark
...
ISBN                : 9780307276735

$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/pcloud/Media/Books/ show_metadata 48
Title               : Dexter in the Dark
...
ISBN                : 9780307276735

# make an update through the pcloud client
$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/Books/ remove 48

# Book properly removed in pcloud client (error fetching it)
$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/Books/ show_metadata 48
TypeError: %d format: a number is required, not builtin_function_or_method

# But still present through rclone
$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/pcloud/Media/Books/ show_metadata 48
Title               : Dexter in the Dark
...
ISBN                : 9780307276735

# files are now diverging, even after 10min
$ stat ~/Books/metadata.db
16777221 40101755 -rw-r--r-- 1 yann staff 0 10625024 "Sep 16 08:11:59 2021" "Sep 16 08:11:59 2021" "Sep 16 08:11:59 2021" "Sep 11 14:20:04 2021" 4096 20992 0 /Users/yann/Books/metadata.db

$ stat ~/pcloud/Media/Books/metadata.db
889192459 4 -rw-r--r-- 1 yann staff 0 10625024 "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" "Sep 16 07:50:05 2021" 4096 20752 0 /Users/yann/pcloud/Media/Books/metadata.db

# clear cache
$ kill -SIGHUP 4370

# new timestamps are updated
$ stat ~/pcloud/Media/Books/metadata.db
889192459 4 -rw-r--r-- 1 yann staff 0 10625024 "Sep 16 08:11:59 2021" "Sep 16 08:11:59 2021" "Sep 16 08:11:59 2021" "Sep 16 08:11:59 2021" 4096 20752 0 /Users/yann/pcloud/Media/Books/metadata.db

# but file update still not reflected
$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/pcloud/Media/Books/ show_metadata 48
Title               : Dexter in the Dark
...
ISBN                : 9780307276735

# Restart rclone mount: the update is now visible
$ /Applications/calibre.app/Contents/MacOS/calibredb --with-library=~/pcloud/Media/Books/ show_metadata 48
TypeError: %d format: a number is required, not builtin_function_or_method
```

Note that these tests using Calibre and a big (~10Mb) binary file seem to be necessary, as similar tests using a simple text file are showing the updates properly reflected after a short while.

My conclusion is that, at least for large binary files, rclone appears not to receive / detect remote file updates from pcloud after an initial read, and until a restart. So my issue title is actually not correct, writes seem to be uploaded fine, only the reads aren't reflected. I suspect that _subsequent_ writes are also failing to upload, but not getting the original update from pcloud is the first issue here.

The intriguing log entry is in my opinion this one, which seems to indicate that the VFS cache entry for this file is never cleared:

```
vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item Media/Books/metadata.db not removed, freed 0 bytes
```

I don't think this has to do with conflicts after all.

I've attached logs for a different run (so timestamps won't match), but similar flow of the commands above.

[rclone-1.logs.zip](https://github.com/rclone/rclone/files/7175544/rclone-1.logs.zip)

**Comment by ncw** [comment]
pcloud doesn't have a mechanism (at least one we've implemented) to tell rclone about changes.

This means that you'l have to wait for the directory cache to expire in order to see changes on the remote

    --dir-cache-time duration   Time to cache directory entries for. (default 5m0s)

> The intriguing log entry is in my opinion this one, which seems to indicate that the VFS cache entry for this file is never cleared:
> 
> ```
> vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item Media/Books/metadata.db not removed, freed 0 bytes
> ```

What that is telling you is that the file is still open and rclone hasn't uploaded it yet - it will do so once it is closed. Quitting Calibre should do that.

**Comment by Yann-J** [comment]
Hmm ok, then that's a bit confusing since:

* The file is still stale even after `dir-cache-time`, and after forcing rclone to clear it (sending a `SIGHUP`). This only seems to update the timestamps
* There is definitely no process keeping a lock on the `metadata.db` file (all updates are done through one-off command line, there's no separate calibre process running), so there should be no reason for rclone to consider it locked. I can try some other test cases just to rule out any calibre-specific weirdness, but I'm fully confident that the file gets released properly.

**Comment by ncw** [comment]
It could be a bug of course!

Can you try cache mode writes and full? Minimal is the least used so most likely to have problems.

**Comment by ivandeex** [comment]
@ncw

> > try this:
> > 1. stop your container
> > `docker volume set rclone args="-vv --vfs-cache-mode=minimal"`
> > **UPDATE** also put `--vfs-cache-mode=minimal` in the `docker volume create`.
>
> Thanks, indeed lowering the caching level seems to help

Minimal cache mode was reported to help while mounting in docker

**Comment by ncw** [comment]
Hmm... so it went wrong with --vfs-cache-mode full too. This will be easier to debug with mount I think so confirmation that it goes wrong with mount too would be useful.
