### ISSUE TITLE
v1.56.1 panics on Darwin 10.15.7 x86_64 when built with Go 1.17

### ISSUE THREAD

**Issue by herbygillot** [rclone/rclone#5611]
#### What is the problem you are having with rclone?

When `v1.56.1` is compiled with Go 1.17 using a simple `go build`, the resulting binary panics immediately when run with the following trace.

This issue is fixed on latest master, I think it was resolved when all deps were updated.  Can we cut a new minor version to fix? `v1.56.2`?

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff69eed70a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff69eed70a
stack: frame={sp:0x7ffeefbff5e8, fp:0x7ffeefbff638} stack=[0x7ffeefb80688,0x7ffeefbff6f0)
0x00007ffeefbff4e8:  0x01007ffeefbff508  0x0000000000000004 
0x00007ffeefbff4f8:  0x000000000000001f  0x00007fff69eed70a 
0x00007ffeefbff508:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff518:  0x0000000004038cf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff5b8 
0x00007ffeefbff528:  0x000000000573e989  0x00007ffeefbff570 
0x00007ffeefbff538:  0x0000000004038fa8 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000683eb40 
0x00007ffeefbff548:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff558:  0x00007ffeefbff5b8  0x0000000004038cf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff568:  0x000000000683eb40  0x00007ffeefbff5a8 
0x00007ffeefbff578:  0x0000000004038f30 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff588 
0x00007ffeefbff588:  0x0000000004038f60 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000683eb40 
0x00007ffeefbff598:  0x0000000004038cf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff5b8 
0x00007ffeefbff5a8:  0x00007ffeefbff5d8  0x0000000004038cf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff5b8:  0x00007ffeefbff5c0  0x0000000004038d20 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff5c8:  0x00000000057608d7  0x000000000000002a 
0x00007ffeefbff5d8:  0x00007ffeefbff628  0x000000000404f776 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff5e8: <0x00000000057608d7  0x000000000683eb40 
0x00007ffeefbff5f8:  0x00007ffeefbff668  0x0000000004029bc6 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff608:  0x0000000006858068  0x0000000000002000 
0x00007ffeefbff618:  0x00007ffe00000008  0x000000000402a871 <runtime.addspecial+0x0000000000000191> 
0x00007ffeefbff628:  0x00007ffeefbff670 !0x00007fff69eed70a 
0x00007ffeefbff638: >0x00007ffeefbff670  0x0000000006774000 
0x00007ffeefbff648:  0x0000000000000b95  0x000000000418f425 <golang.org/x/sys/unix.libc_umask_trampoline+0x0000000000000005> 
0x00007ffeefbff658:  0x000000000406f61f <runtime.syscall+0x000000000000001f>  0x000000c000837a00 
0x00007ffeefbff668:  0x00007ffeefbff6b0  0x000000c0008379d0 
0x00007ffeefbff678:  0x000000000406d470 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff688:  0x0000000004013400 <runtime.growWork+0x0000000000000040>  0x3400000000000020 
0x00007ffeefbff698:  0x000000000402f905 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x0000000006874060 
0x00007ffeefbff6a8:  0x0000000000000658  0x000000c0000001a0 
0x00007ffeefbff6b8:  0x000000000406b589 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff6c8:  0x0000000005a245f8  0x000000000683eb40 
0x00007ffeefbff6d8:  0x00007ffeefbff720  0x000000000406b485 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff6e8:  0x000000000406b43d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x57608d7, 0x683eb40})
	/opt/local/lib/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff69eed70a
stack: frame={sp:0x7ffeefbff5e8, fp:0x7ffeefbff638} stack=[0x7ffeefb80688,0x7ffeefbff6f0)
0x00007ffeefbff4e8:  0x01007ffeefbff508  0x0000000000000004 
0x00007ffeefbff4f8:  0x000000000000001f  0x00007fff69eed70a 
0x00007ffeefbff508:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff518:  0x0000000004038cf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff5b8 
0x00007ffeefbff528:  0x000000000573e989  0x00007ffeefbff570 
0x00007ffeefbff538:  0x0000000004038fa8 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000683eb40 
0x00007ffeefbff548:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff558:  0x00007ffeefbff5b8  0x0000000004038cf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff568:  0x000000000683eb40  0x00007ffeefbff5a8 
0x00007ffeefbff578:  0x0000000004038f30 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff588 
0x00007ffeefbff588:  0x0000000004038f60 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000683eb40 
0x00007ffeefbff598:  0x0000000004038cf1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff5b8 
0x00007ffeefbff5a8:  0x00007ffeefbff5d8  0x0000000004038cf1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff5b8:  0x00007ffeefbff5c0  0x0000000004038d20 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff5c8:  0x00000000057608d7  0x000000000000002a 
0x00007ffeefbff5d8:  0x00007ffeefbff628  0x000000000404f776 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff5e8: <0x00000000057608d7  0x000000000683eb40 
0x00007ffeefbff5f8:  0x00007ffeefbff668  0x0000000004029bc6 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff608:  0x0000000006858068  0x0000000000002000 
0x00007ffeefbff618:  0x00007ffe00000008  0x000000000402a871 <runtime.addspecial+0x0000000000000191> 
0x00007ffeefbff628:  0x00007ffeefbff670 !0x00007fff69eed70a 
0x00007ffeefbff638: >0x00007ffeefbff670  0x0000000006774000 
0x00007ffeefbff648:  0x0000000000000b95  0x000000000418f425 <golang.org/x/sys/unix.libc_umask_trampoline+0x0000000000000005> 
0x00007ffeefbff658:  0x000000000406f61f <runtime.syscall+0x000000000000001f>  0x000000c000837a00 
0x00007ffeefbff668:  0x00007ffeefbff6b0  0x000000c0008379d0 
0x00007ffeefbff678:  0x000000000406d470 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff688:  0x0000000004013400 <runtime.growWork+0x0000000000000040>  0x3400000000000020 
0x00007ffeefbff698:  0x000000000402f905 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x0000000006874060 
0x00007ffeefbff6a8:  0x0000000000000658  0x000000c0000001a0 
0x00007ffeefbff6b8:  0x000000000406b589 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff6c8:  0x0000000005a245f8  0x000000000683eb40 
0x00007ffeefbff6d8:  0x00007ffeefbff720  0x000000000406b485 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff6e8:  0x000000000406b43d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/opt/local/lib/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x418f420, 0x0, 0x0, 0x0)
	/opt/local/lib/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000837a00 sp=0xc0008379e0 pc=0x4069fdb
syscall.syscall(0x0, 0x0, 0x5768698, 0x2e)
	<autogenerated>:1 +0x26 fp=0xc000837a48 sp=0xc000837a00 pc=0x406fe26
golang.org/x/sys/unix.Umask(0xc000b3e800)
	/Users/herby/go/pkg/mod/golang.org/x/sys@v0.0.0-20210423185535-09eb48e85fd7/unix/zsyscall_darwin_amd64.go:2143 +0x34 fp=0xc000837a78 sp=0xc000837a48 pc=0x418ee74
github.com/rclone/rclone/vfs/vfsflags.platformFlags(0x54136e0)
	/Users/herby/Source/rclone/vfs/vfsflags/vfsflags_unix.go:14 +0x25 fp=0xc000837ad8 sp=0xc000837a78 pc=0x5160d05
github.com/rclone/rclone/vfs/vfsflags.AddFlags(0xc0001a4280)
	/Users/herby/Source/rclone/vfs/vfsflags/vfsflags.go:41 +0x4c9 fp=0xc000837b38 sp=0xc000837ad8 pc=0x5160ca9
github.com/rclone/rclone/cmd/mountlib.NewMountCommand({0x570161e, 0x6}, 0x1, 0x57e9040)
	/Users/herby/Source/rclone/cmd/mountlib/mount.go:164 +0x20f fp=0xc000837ba8 sp=0xc000837b38 pc=0x51616cf
github.com/rclone/rclone/cmd/mount2.init.0()
	/Users/herby/Source/rclone/cmd/mount2/mount.go:21 +0x31 fp=0xc000837bd8 sp=0xc000837ba8 pc=0x5166a11
runtime.doInit(0x67884e0)
	/opt/local/lib/go/src/runtime/proc.go:6498 +0x123 fp=0xc000837d10 sp=0xc000837bd8 pc=0x40488c3
runtime.doInit(0x6798e80)
	/opt/local/lib/go/src/runtime/proc.go:6475 +0x71 fp=0xc000837e48 sp=0xc000837d10 pc=0x4048811
runtime.doInit(0x677b860)
	/opt/local/lib/go/src/runtime/proc.go:6475 +0x71 fp=0xc000837f80 sp=0xc000837e48 pc=0x4048811
runtime.main()
	/opt/local/lib/go/src/runtime/proc.go:238 +0x1e6 fp=0xc000837fe0 sp=0xc000837f80 pc=0x403b606
runtime.goexit()
	/opt/local/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000837fe8 sp=0xc000837fe0 pc=0x406d761

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000d2b80)
	/Users/herby/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/Users/herby/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92

```

#### What is your rclone version (output from `rclone version`)
Git checkout is from git tag `v1.56.1` - cannot use `rclone version` because `rclone` panics on startup.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
64-bit Darwin: macOS Catalina, 10.15.7

#### Which cloud storage system are you using? (e.g. Google Drive)
N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`./rclone`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Panics on startup, no log. Trace is included above.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
That is interesting...

1.56.1 was compiled with go1.16 for the release binaries as was 1.56 - I keep the same major version of the go binary for the point releases.

Updating all the deps is too much change for a stable release, but I'd consider updating just the one library if we can find out which one.

I would think the most likely suspect is `golang.org/x/sys/unix`

Can you try upgrading just that library?

So check out rclone v1.56.1 then

    go get golang.org/x/sys/unix

And test.

If that works (or you find which library it is) then please submit a PR against the v1.56-stable branch

**Comment by darthShadow** [comment]
Probably this: https://github.com/rclone/rclone/commit/8bd26c663ab19eaded9769a73dcb956f653276f6

**Comment by herbygillot** [comment]
Thank you @ncw, @darthShadow.  @ncw, it's confirmed that your commit that @darthShadow references fixes the issue.

I have a pull request to bring this commit into `v1.56-stable` as requested at #5614

**Comment by ncw** [comment]
I've merged this now.

Binaries will be available here

[v1.56.2-beta.5623.e75d57d63.v1.56-stable](https://beta.rclone.org/branch/v1.56-stable/v1.56.2-beta.5623.e75d57d63.v1.56-stable/) on branch [v1.56-stable](https://github.com/rclone/rclone/tree/v1.56-stable) (uploaded in 15-30 mins)

**Comment by herbygillot** [comment]
Thank you @ncw

**Comment by ncw** [comment]
BTW v1.56.2 has been released with this fix in :-)

**Comment by herbygillot** [comment]
Thank you @ncw, I had already updated `rclone` in [MacPorts](https://www.macports.org) to `v1.56.2`:

https://ports.macports.org/port/rclone/
