### ISSUE TITLE
Crash Dropbox backend with invalid impersonate user

### ISSUE THREAD

**Issue by timwsuqld** [rclone/rclone#6139]
#### What is the problem you are having with rclone?
When an invalid `impersonate` user is used for the Dropbox backend we get a segfault. (Caused by a typo in a config file when I was changing which user I needed to impersonate)

I assume an API call failed and rclone didn't catch it and so continues assuming we have a valid login. It would be good to catch this failed call and show an API error instead.

#### What is your rclone version (output from `rclone version`)
```
rclone --version
rclone v1.58.1
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.13.0-40-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.04 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone --config=rclone.conf lsd 'WA-Dropbox:/' -vv`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
<7>DEBUG : rclone: Version "v1.58.1" starting with parameters ["rclone" "--config=rclone.conf" "lsd" "WA-Dropbox:/" "-vv"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "WA-Dropbox:/"
<7>DEBUG : Using config file from "/home/timw/src/rclone-ps-migration/rclone.conf"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd33eb0]

goroutine 1 [running]:
github.com/rclone/rclone/backend/dropbox.NewFs({0x1f203e8, 0xc0000500b0}, {0x7ffc87a1916e, 0x1f}, {0x7ffc87a19179, 0x1}, {0x1eff2e8, 0xc00061eff0})
	github.com/rclone/rclone/backend/dropbox/dropbox.go:480 +0xa50
github.com/rclone/rclone/fs.NewFs({0x1f203e8, 0xc0000500b0}, {0x7ffc87a1916e, 0xc})
	github.com/rclone/rclone/fs/newfs.go:51 +0x279
github.com/rclone/rclone/fs/cache.GetFn.func1({0x100000000000b, 0xc000537a68})
	github.com/rclone/rclone/fs/cache/cache.go:62 +0x3b
github.com/rclone/rclone/lib/cache.(*Cache).Get(0xc00089f8c0, {0x7ffc87a1916e, 0x26c}, 0xc000537b78)
	github.com/rclone/rclone/lib/cache/cache.go:86 +0xeb
github.com/rclone/rclone/fs/cache.GetFn({0x1f203e8, 0xc0000500b0}, {0x7ffc87a1916e, 0xc}, 0x1bf2a50)
	github.com/rclone/rclone/fs/cache/cache.go:61 +0x136
github.com/rclone/rclone/fs/cache.Get({0x1f203e8, 0xc0000500b0}, {0x7ffc87a1916e, 0xc})
	github.com/rclone/rclone/fs/cache/cache.go:127 +0x6f
github.com/rclone/rclone/cmd.NewFsFile({0x7ffc87a1916e, 0xc})
	github.com/rclone/rclone/cmd/cmd.go:96 +0x108
github.com/rclone/rclone/cmd.newFsFileAddFilter({0x7ffc87a1916e, 0xc})
	github.com/rclone/rclone/cmd/cmd.go:117 +0x66
github.com/rclone/rclone/cmd.NewFsSrc(...)
	github.com/rclone/rclone/cmd/cmd.go:139
github.com/rclone/rclone/cmd/lsd.glob..func1(0x2cf2140, {0xc00089f7d0, 0x3, 0x3})
	github.com/rclone/rclone/cmd/lsd/lsd.go:57 +0xa5
github.com/spf13/cobra.(*Command).execute(0x2cf2140, {0xc00089f7a0, 0x3, 0x3})
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2ceae40)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/rclone/rclone/cmd.Main()
	github.com/rclone/rclone/cmd/cmd.go:553 +0x76
main.main()
	github.com/rclone/rclone/rclone.go:14 +0x17
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Can you share the rclone.conf?

**Comment by timwsuqld** [comment]
> Can you share the rclone.conf?

Not much to it. Pretty standard config, using custom client_id and secret, and using the impersonate feature as it's a Teams account and we needed to move files as some of our users.

```
[WA-Dropbox]
type = dropbox
client_id = <customID>
client_secret = <customSecret>
token = <accessToken>
impersonate = misstypedemail@domain.com
```

**Comment by ncw** [comment]
Can you give this a go @timwsuqld ?

It looks like the API didn't return an error, it just returned a structure with lots of nasty `nil` pointers!

[v1.59.0-beta.6115.5523201d2.fix-6139-dropbox-impersonate](https://beta.rclone.org/branch/fix-6139-dropbox-impersonate/v1.59.0-beta.6115.5523201d2.fix-6139-dropbox-impersonate/) on branch [fix-6139-dropbox-impersonate](https://github.com/rclone/rclone/tree/fix-6139-dropbox-impersonate) (uploaded in 15-30 mins)
