### ISSUE TITLE
Possible bug 1.59.3: S3 to S3 transfer (worked with 1.58.1)

### ISSUE THREAD

**Issue by BernhardGruen** [rclone/rclone#6322]
Hello,

We are using rclone to transfer files between S3 buckets (disaster recovery plan).
Using **1.59.0** we get a strange error. This error is reproducible. Using version 1.58.1 of rclone everything worked fine. 
If it matters we are using the bitnami/rclone docker image.

This is the command we use:
```shell
rclone --config /tmp/rclones.conf \
    copy s3-source:/bucket-source s3-target:/bucket-target \
    -P --stats 10s --stats-log-level NOTICE --max-backlog 20000 --checkers=96 --transfers=32 \
    --buffer-size 4Mi --checksum --tpslimit 150 --s3-no-head --s3-no-head-object --fast-list
```
In case it matters we copy files from DigitalOcean Spaces (FRA1) to ScaleWay Object Storage (PAR). The source bucket has about 1.1 mio objects (target about the same).

This is the error message we see:
```
panic: reflect: Elem of invalid type s3.PutObjectInput

goroutine 258 [running]:
reflect.(*rtype).Elem(0x0?)
	/usr/local/go-1.18.4/src/reflect/type.go:965 +0x134
github.com/rclone/rclone/lib/structs.SetFrom({0x27b54e0?, 0xc1788e4480}, {0x27d9ec0?, 0xc1787568c0})
	/bitnami/blacksmith-sandox/rclone-1.59.0/src/github.com/rclone/rclone/lib/structs/structs.go:22 +0xdf
github.com/rclone/rclone/backend/s3.(*Object).Update(0xc16927b0e0, {0x2c95da0, 0xc000640700}, {0x2c842c0, 0xc16991e700}, {0x2c9d518?, 0xc016435320?}, {0xc1697c8830, 0x1, 0x1})
	/bitnami/blacksmith-sandox/rclone-1.59.0/src/github.com/rclone/rclone/backend/s3/s3.go:4573 +0x1345
github.com/rclone/rclone/backend/s3.(*Fs).Put(0xc00037ed80, {0x2c95da0, 0xc000640700}, {0x2c842c0, 0xc16991e700}, {0x2c9d518?, 0xc016435320?}, {0xc1697c8830, 0x1, 0x1})
	/bitnami/blacksmith-sandox/rclone-1.59.0/src/github.com/rclone/rclone/backend/s3/s3.go:3085 +0x125
github.com/rclone/rclone/fs/operations.Copy({0x2c95da0, 0xc000640700}, {0x2ca66d0, 0xc00037ed80}, {0x0?, 0x0?}, {0xc0161ef810, 0x68}, {0x2ca6740, 0xc016435320})
	/bitnami/blacksmith-sandox/rclone-1.59.0/src/github.com/rclone/rclone/fs/operations/operations.go:501 +0x1b24
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00049efc0, {0x2c95da0, 0xc000640700}, 0x0?, {0x2ca66d0, 0xc00037ed80}, 0x0?, 0x0?)
	/bitnami/blacksmith-sandox/rclone-1.59.0/src/github.com/rclone/rclone/fs/sync/sync.go:416 +0x1bb
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
	/bitnami/blacksmith-sandox/rclone-1.59.0/src/github.com/rclone/rclone/fs/sync/sync.go:443 +0x45
```

I assume the error is printend after fast-list has finished its work because it took about 17 minutes to get there and there were no`checking` or `transfering` output.

If more information is needed I can try to provide that.

**Comment by ncw** [comment]
This is definitely a bug! I can replicate the problem.

It was a silly problem, which shows this code path is not integration tested, so I've fixed the problem and added an integration test so it won't happen again!

Please give this a go

[v1.60.0-beta.6363.6e1a3e044.fix-6322-s3-no-head](https://beta.rclone.org/branch/fix-6322-s3-no-head/v1.60.0-beta.6363.6e1a3e044.fix-6322-s3-no-head/) on branch [fix-6322-s3-no-head](https://github.com/rclone/rclone/tree/fix-6322-s3-no-head) (uploaded in 15-30 mins)

If that works for you, I'll merge into 1.60 and 1.59.1

**Comment by BernhardGruen** [comment]
@ncw 
Thank you for your quick reaction.
Please give me some time as I am not at home at the moment.
I will test it once I am back home (this evening).

**Comment by BernhardGruen** [comment]
Hey @ncw 
I am really sorry for the late response to your question.
I just tested the beta version of 1.60 that contains the fix. It seems to work correctly now. Thank you!
Also sorry for not identifying that `--s3-no-head` could be the root cause of the issue. Because the list (using `--fast-list`) alone took quite some time (about 17 minutes) I was a bit too lazy to test if a specific option could cause / circumvent that issue. My quick "fix" was to go back to the last working version.

**Comment by ncw** [comment]
@BernhardGruen no need to be sorry - the bug report was excellent and the panic showed exactly where the problem was.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.60. I'll also release it in 1.59.1
