### ISSUE TITLE
wrong implementation of RCD Mount with daemon parameter

### ISSUE THREAD

**Issue by segator** [rclone/rclone#6469]
if you mount a volume using rclone rc or web gui passing as  mount command parameter **daemon**. RCD is not running rclone mount command properly, seems is pasing RCD arguments instead of building the proper mount args, you can find it clear here https://github.com/rclone/rclone/blob/master/cmd/mountlib/mount.go#L249, making the mount is never mounted, also will make crash when trying to unmount as unmountFn() is nil
```
error: invalid memory address or nil pointer dereference
goroutine 83 [running]:
runtime/debug.Stack()
        /root/sdk/go1.19.1/src/runtime/debug/stack.go:24 +0x7a
github.com/rclone/rclone/fs/rc/jobs.(*Job).run.func1()
        /root/rclone/fs/rc/jobs/job.go:90 +0x55
panic({0x3060b00, 0x44cfc10})
        /root/sdk/go1.19.1/src/runtime/panic.go:890 +0x267
github.com/rclone/rclone/cmd/mountlib.(*MountPoint).Unmount(0xc0006f4480)
        /root/rclone/cmd/mountlib/mount.go:324 +0x2c
github.com/rclone/rclone/cmd/mountlib.unMountRc({0x7fd804a10fff, 0xc00053ed90},
0xc0005f17a0)
        /root/rclone/cmd/mountlib/rc.go:167 +0x1f1
github.com/rclone/rclone/fs/rc/jobs.(*Job).run(0xc0008c0840, {0x38517f0, 0xc0003
48c00}, 0x34cfd18, 0xc0005f17a0)
        /root/rclone/fs/rc/jobs/job.go:93 +0xd9
github.com/rclone/rclone/fs/rc/jobs.(*Jobs).NewJob(0xc0006f0090, {0x38517f0, 0xc
000348c00}, 0x34cfd18, 0xc0005f17a0)
        /root/rclone/fs/rc/jobs/job.go:286 +0x930
github.com/rclone/rclone/fs/rc/jobs.NewJob({0x38517f0, 0xc000348bc0}, 0x34cfd18,
 0xc0005f1740)
        /root/rclone/fs/rc/jobs/job.go:296 +0xa5
github.com/rclone/rclone/fs/rc/rcserver.(*Server).handlePost(0xc00014b600, {0x38
4e1b0, 0xc0008b4700}, 0xc000c18300, {0xc0005f20a6, 0xd})
        /root/rclone/fs/rc/rcserver/rcserver.go:280 +0xd86
github.com/rclone/rclone/fs/rc/rcserver.(*Server).handler(0xc00014b600, {0x384e1
b0, 0xc0008b4700}, 0xc000c18300)
        /root/rclone/fs/rc/rcserver/rcserver.go:213 +0x431
net/http.HandlerFunc.ServeHTTP(0xc000580840, {0x384e1b0, 0xc0008b4700}, 0xc000c1
8300)
        /root/sdk/go1.19.1/src/net/http/server.go:2109 +0x43
net/http.(*ServeMux).ServeHTTP(0x45abd80, {0x384e1b0, 0xc0008b4700}, 0xc000c1830
0)
        /root/sdk/go1.19.1/src/net/http/server.go:2487 +0x135
net/http.serverHandler.ServeHTTP({0xc000430870}, {0x384e1b0, 0xc0008b4700}, 0xc0
00c18300)
        /root/sdk/go1.19.1/src/net/http/server.go:2947 +0x474
net/http.(*conn).serve(0xc000d14500, {0x38517f0, 0xc000ccc000})
        /root/sdk/go1.19.1/src/net/http/server.go:1991 +0x195c
created by net/http.(*Server).Serve
        /root/sdk/go1.19.1/src/net/http/server.go:3102 +0x9e5
```

**Version 1.59.2** Tried aswell with development version master https://github.com/rclone/rclone/commit/7fbc928a19431f566b87c8c33d98fbb5099dad5f

**Comment by ncw** [comment]
Yes I think blocking the option via the RC is the right thing to do.

Want to send a PR?

**Comment by segator** [comment]
Maybe next weekend

**Comment by ncw** [comment]
Just return an error `Daemon not supported over the API` or something like that if you see the Daemon flag is set and that will make its way back to the user.
