### ISSUE TITLE
rclone crashes when reading file metadata in Android

### ISSUE THREAD

**Issue by iikira** [rclone/rclone#7006]
#### What is the problem you are having with rclone?
When reading the file metadata in android, rclone will report 'bad system call' and then exit

#### What is your rclone version (output from `rclone version`)
I compiled rclone with GOOS=android GOARCH=arm64, and the source code uses the release version of v1.62.2

rclone v1.62.2-DEV
- os/version: unknown
- os/kernel: 4.9.179-perf+ (aarch64)
- os/type: android
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.20.1
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Android 10, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
local

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
~/tmp $ ls
a.txt
~/tmp $ rclone -vvv copyto --metadata a.txt b.txt
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2023/05/17 02:33:48 DEBUG : rclone: Version "v1.62.2-DEV" starting with parameters ["rclone" "-vvv" "copyto" "--metadata" "a.txt" "b.txt"]
2023/05/17 02:33:48 DEBUG : Creating backend with remote "a.txt"
2023/05/17 02:33:48 DEBUG : Using config file from "/data/data/com.termux/files/home/.config/rclone/rclone.conf"
2023/05/17 02:33:49 DEBUG : fs cache: adding new entry for parent of "a.txt", "/data/data/com.termux/files/home/tmp"
2023/05/17 02:33:49 DEBUG : Creating backend with remote "."
2023/05/17 02:33:49 DEBUG : fs cache: renaming cache item "." to be canonical "/data/data/com.termux/files/home/tmp"
2023/05/17 02:33:49 DEBUG : a.txt: Need to transfer - File not found at Destination
SIGSYS: bad system call
PC=0x5b068952c0 m=0 sigcode=1

goroutine 1 [syscall]:
syscall.Syscall6(0x4000927098?, 0x5b06a4244c?, 0x5b0685bd10?, 0x1?, 0x0?, 0x5b0685bd10?, 0x40009c3da0?)
	/usr/local/go/src/syscall/syscall_linux.go:91 +0x2c fp=0x4000927050 sp=0x4000926fc0 pc=0x5b0692009c
syscall.Syscall6(0x123, 0xffffffffffffff9c, 0x40009c9620, 0x0, 0xfff, 0x4000927178, 0x0)
	<autogenerated>:1 +0x2c fp=0x40009270a0 sp=0x4000927050 pc=0x5b06920cac
golang.org/x/sys/unix.Statx(0x40009ec540?, {0x5b0685bd10?, 0x4000927238?}, 0x5b073f5058?, 0x40000cd000?, 0x4000927178)
	/Users/syy/go/pkg/mod/golang.org/x/sys@v0.6.0/unix/zsyscall_linux.go:1589 +0xa8 fp=0x4000927140 sp=0x40009270a0 pc=0x5b06a424b8
github.com/rclone/rclone/backend/local.(*Object).readMetadataFromFile.func1()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/metadata_linux.go:26 +0x58 fp=0x4000927280 sp=0x4000927140 pc=0x5b073f54c8
sync.(*Once).doSlow(0x8?, 0x5b07fa35c0?)
	/usr/local/go/src/sync/once.go:74 +0x100 fp=0x40009272e0 sp=0x4000927280 pc=0x5b06912ee0
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/rclone/rclone/backend/local.(*Object).readMetadataFromFile(0x400012b020?, 0x5b06c0d82c?)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/metadata_linux.go:22 +0x44 fp=0x4000927310 sp=0x40009272e0 pc=0x5b073f3fa4
github.com/rclone/rclone/backend/local.(*Object).Metadata(0x4000927388?, {0x7a489c5e10?, 0x400012b020?})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/local.go:1385 +0xac fp=0x4000927350 sp=0x4000927310 pc=0x5b073f37ac
github.com/rclone/rclone/fs.(*OverrideRemote).Metadata(0x40009273c8?, {0x5b0832d3b8, 0x4000056058})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/override.go:65 +0x54 fp=0x4000927390 sp=0x4000927350 pc=0x5b06c0d844
github.com/rclone/rclone/fs.GetMetadata({0x5b0832d3b8, 0x4000056058}, {0x5b083360b0?, 0x400007c420?})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/metadata.go:66 +0x54 fp=0x40009273d0 sp=0x4000927390 pc=0x5b06c0a244
github.com/rclone/rclone/fs.GetMetadataOptions({0x5b0832d3b8, 0x4000056058}, {0x5b083360b0, 0x400007c420}, {0x40004e1300, 0x1, 0x0?})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/metadata.go:79 +0x58 fp=0x40009274a0 sp=0x40009273d0 pc=0x5b06c0a2f8
github.com/rclone/rclone/backend/local.(*Object).Update(0x400012b140, {0x5b0832d3b8, 0x4000056058}, {0x5b08317540, 0x40009d2b00}, {0x5b083360b0?, 0x400007c420?}, {0x40004e1300?, 0x1, 0x1})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/local.go:1270 +0x5f4 fp=0x4000927590 sp=0x40009274a0 pc=0x5b073f3114
github.com/rclone/rclone/backend/local.(*Fs).Put(0x40009697c0?, {0x5b0832d3b8, 0x4000056058}, {0x5b08317540, 0x40009d2b00}, {0x5b083360b0?, 0x400007c420?}, {0x40004e1300, 0x1, 0x1})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/local.go:598 +0x90 fp=0x4000927610 sp=0x4000927590 pc=0x5b073efe00
github.com/rclone/rclone/fs/operations.Copy({0x5b0832d3b8, 0x4000056058}, {0x5b0833f160, 0x4000969680}, {0x0?, 0x0?}, {0x7fcdabd506, 0x5}, {0x5b0833f1d0?, 0x400012b020})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/operations/operations.go:440 +0x1420 fp=0x4000927890 sp=0x4000927610 pc=0x5b06f502c0
github.com/rclone/rclone/fs/operations.moveOrCopyFile({0x5b0832d3b8, 0x4000056058}, {0x5b0833f160, 0x4000969680}, {0x5b0833f160?, 0x4000969680?}, {0x7fcdabd506, 0x5}, {0x7fcdabd500, 0x5}, ...)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/operations/operations.go:1934 +0x724 fp=0x4000927a40 sp=0x4000927890 pc=0x5b06f5af24
github.com/rclone/rclone/fs/operations.CopyFile(...)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/operations/operations.go:1954
github.com/rclone/rclone/cmd/copyto.glob..func1.1()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/cmd/copyto/copyto.go:59 +0x84 fp=0x4000927ab0 sp=0x4000927a40 pc=0x5b07adcb74
github.com/rclone/rclone/cmd.Run(0x1, 0x1, 0x2?, 0x4000927cb0)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/cmd/cmd.go:257 +0x100 fp=0x4000927c70 sp=0x4000927ab0 pc=0x5b07abe0e0
github.com/rclone/rclone/cmd/copyto.glob..func1(0x5b09332800?, {0x40000a08c0, 0x2, 0x4})
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/cmd/copyto/copyto.go:55 +0xac fp=0x4000927d00 sp=0x4000927c70 pc=0x5b07adcaac
github.com/spf13/cobra.(*Command).execute(0x5b09332800, {0x40000a0880, 0x4, 0x4})
	/Users/syy/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5ac fp=0x4000927e40 sp=0x4000927d00 pc=0x5b07a95cfc
github.com/spf13/cobra.(*Command).ExecuteC(0x5b0932d1c0)
	/Users/syy/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340 fp=0x4000927f00 sp=0x4000927e40 pc=0x5b07a964d0
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/syy/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/rclone/rclone/cmd.Main()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/cmd/cmd.go:567 +0x6c fp=0x4000927f60 sp=0x4000927f00 pc=0x5b07abf99c
main.main()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/rclone.go:14 +0x1c fp=0x4000927f70 sp=0x4000927f60 pc=0x5b07cb933c
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x200 fp=0x4000927fd0 sp=0x4000927f70 pc=0x5b068cf740
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000927fd0 sp=0x4000927fd0 pc=0x5b069047d4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000074fa0 sp=0x4000074f80 pc=0x5b068cfb50
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0x4000074fd0 sp=0x4000074fa0 pc=0x5b068cf9a0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000074fd0 sp=0x4000074fd0 pc=0x5b069047d4
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000075760 sp=0x4000075740 pc=0x5b068cfb50
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:319 +0x100 fp=0x40000757b0 sp=0x4000075760 pc=0x5b068b8e70
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x40000757d0 sp=0x40000757b0 pc=0x5b068adc28
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000757d0 sp=0x40000757d0 pc=0x5b069047d4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x400007e000?, 0x5b0685b318?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000075f50 sp=0x4000075f30 pc=0x5b068cfb50
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x5b0934efa0)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x5c fp=0x4000075f80 sp=0x4000075f50 pc=0x5b068b6ccc
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:633 +0xa8 fp=0x4000075fb0 sp=0x4000075f80 pc=0x5b068b7288
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x4000075fd0 sp=0x4000075fb0 pc=0x5b068adbc8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000075fd0 sp=0x4000075fd0 pc=0x5b069047d4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xac

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x5b093505e0?, 0xc0?, 0x36?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000074580 sp=0x4000074560 pc=0x5b068cfb50
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x100 fp=0x40000747d0 sp=0x4000074580 pc=0x5b068accf0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000747d0 sp=0x40000747d0 pc=0x5b069047d4
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x80

goroutine 34 [select]:
runtime.gopark(0x4000076778?, 0x3?, 0x90?, 0x80?, 0x4000076762?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000076610 sp=0x40000765f0 pc=0x5b068cfb50
runtime.selectgo(0x4000076778, 0x400007675c, 0x40002cad80?, 0x0, 0x400004e4e0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x68c fp=0x4000076720 sp=0x4000076610 pc=0x5b068e04ac
go.opencensus.io/stats/view.(*worker).start(0x40002cad80)
	/Users/syy/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x88 fp=0x40000767b0 sp=0x4000076720 pc=0x5b0714d7e8
go.opencensus.io/stats/view.init.0.func1()
	/Users/syy/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x28 fp=0x40000767d0 sp=0x40000767b0 pc=0x5b0714c9e8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000767d0 sp=0x40000767d0 pc=0x5b069047d4
created by go.opencensus.io/stats/view.init.0
	/Users/syy/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0xa0

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000070740 sp=0x4000070720 pc=0x5b068cfb50
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x40000707d0 sp=0x4000070740 pc=0x5b068afa04
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000707d0 sp=0x40000707d0 pc=0x5b069047d4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x1ab0f6bad7ecf2?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000076f40 sp=0x4000076f20 pc=0x5b068cfb50
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x4000076fd0 sp=0x4000076f40 pc=0x5b068afa04
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000076fd0 sp=0x4000076fd0 pc=0x5b069047d4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1ab0f6bad9b4ad?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400013a740 sp=0x400013a720 pc=0x5b068cfb50
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x400013a7d0 sp=0x400013a740 pc=0x5b068afa04
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400013a7d0 sp=0x400013a7d0 pc=0x5b069047d4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x1ab0f6bad7f30d?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000070f40 sp=0x4000070f20 pc=0x5b068cfb50
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x4000070fd0 sp=0x4000070f40 pc=0x5b068afa04
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000070fd0 sp=0x4000070fd0 pc=0x5b069047d4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x1ab0f6bad7e740?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000071740 sp=0x4000071720 pc=0x5b068cfb50
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x40000717d0 sp=0x4000071740 pc=0x5b068afa04
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000717d0 sp=0x40000717d0 pc=0x5b069047d4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x1ab0f6bad7f104?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000071f40 sp=0x4000071f20 pc=0x5b068cfb50
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x4000071fd0 sp=0x4000071f40 pc=0x5b068afa04
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000071fd0 sp=0x4000071fd0 pc=0x5b069047d4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 9 [select]:
runtime.gopark(0x400013dfa0?, 0x2?, 0x78?, 0xde?, 0x400013df7c?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400013de20 sp=0x400013de00 pc=0x5b068cfb50
runtime.selectgo(0x400013dfa0, 0x400013df78, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x68c fp=0x400013df30 sp=0x400013de20 pc=0x5b068e04ac
github.com/rclone/rclone/cmd.StartStats.func2()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/cmd/cmd.go:372 +0xc8 fp=0x400013dfd0 sp=0x400013df30 pc=0x5b07abeee8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400013dfd0 sp=0x400013dfd0 pc=0x5b069047d4
created by github.com/rclone/rclone/cmd.StartStats
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/cmd/cmd.go:368 +0xac

goroutine 10 [select]:
runtime.gopark(0x400013d778?, 0x2?, 0xd8?, 0xd5?, 0x400013d714?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400013d590 sp=0x400013d570 pc=0x5b068cfb50
runtime.selectgo(0x400013d778, 0x400013d710, 0x5b07f13140?, 0x0, 0x400012a598?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x68c fp=0x400013d6a0 sp=0x400013d590 pc=0x5b068e04ac
github.com/rclone/rclone/fs/accounting.(*StatsInfo).averageLoop(0x400029e000)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/accounting/stats.go:328 +0x100 fp=0x400013d7b0 sp=0x400013d6a0 pc=0x5b06dc7bc0
github.com/rclone/rclone/fs/accounting.(*StatsInfo).startAverageLoop.func1.1()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/accounting/stats.go:357 +0x28 fp=0x400013d7d0 sp=0x400013d7b0 pc=0x5b06dc80a8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400013d7d0 sp=0x400013d7d0 pc=0x5b069047d4
created by github.com/rclone/rclone/fs/accounting.(*StatsInfo).startAverageLoop.func1
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/accounting/stats.go:357 +0x70

goroutine 11 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000072660 sp=0x4000072640 pc=0x5b068cfb50
runtime.chanrecv(0x400056d200, 0x4000072768, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x468 fp=0x40000726f0 sp=0x4000072660 pc=0x5b06899a78
runtime.chanrecv2(0x0?, 0x0?)
	/usr/local/go/src/runtime/chan.go:447 +0x14 fp=0x4000072720 sp=0x40000726f0 pc=0x5b068995f4
github.com/rclone/rclone/backend/local.(*fadvise).worker(0x4000457f80)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/fadvise_unix.go:115 +0x3c fp=0x40000727b0 sp=0x4000072720 pc=0x5b073ed72c
github.com/rclone/rclone/backend/local.newFadvise.func1()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/fadvise_unix.go:75 +0x28 fp=0x40000727d0 sp=0x40000727b0 pc=0x5b073ed418
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000727d0 sp=0x40000727d0 pc=0x5b069047d4
created by github.com/rclone/rclone/backend/local.newFadvise
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/backend/local/fadvise_unix.go:75 +0x120

goroutine 12 [select]:
runtime.gopark(0x4000072f80?, 0x2?, 0x8?, 0x2e?, 0x4000072f34?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000072dc0 sp=0x4000072da0 pc=0x5b068cfb50
runtime.selectgo(0x4000072f80, 0x4000072f30, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x68c fp=0x4000072ed0 sp=0x4000072dc0 pc=0x5b068e04ac
github.com/rclone/rclone/fs/accounting.(*Account).averageLoop(0x40009d2b00)
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/accounting/accounting.go:212 +0xb8 fp=0x4000072fb0 sp=0x4000072ed0 pc=0x5b06dc22f8
github.com/rclone/rclone/fs/accounting.newAccountSizeName.func1()
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/accounting/accounting.go:110 +0x28 fp=0x4000072fd0 sp=0x4000072fb0 pc=0x5b06dc1768
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000072fd0 sp=0x4000072fd0 pc=0x5b069047d4
created by github.com/rclone/rclone/fs/accounting.newAccountSizeName
	/Users/syy/go/pkg/mod/github.com/rclone/rclone@v1.62.2/fs/accounting/accounting.go:110 +0x3c4

r0      0xffffffffffffff9c
r1      0x40009c9620
r2      0x0
r3      0xfff
r4      0x4000927178
r5      0x0
r6      0x0
r7      0x40009c9622
r8      0x123
r9      0x40009c9620
r10     0x0
r11     0x0
r12     0x163
r13     0x155
r14     0x13d
r15     0x10325476
r16     0x40009083a0
r17     0x4000927120
r18     0x7a7a0ac000
r19     0x0
r20     0x4000927268
r21     0x40009273b0
r22     0x1
r23     0xffffffffffffffff
r24     0x5b064a6de0
r25     0x61c998f76b01fc20
r26     0x5b08304d40
r27     0x0
r28     0x40000021a0
r29     0x4000926f58
lr      0x5b0689527c
sp      0x4000926f60
pc      0x5b068952c0
fault   0x0
```

#### Possible solution
The statx system call is not directly available in Android. Android system crashes an app that uses an illegal syscall. But executing the above command with root privileges in Android, no errors will occur.

Maybe check if statx system call is available or avoid using statx system call in Android.

See also: 
https://github.com/boostorg/filesystem/issues/229
https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
It would be nice if Android just returned ENOSYS rather than fault the program! It would have fallen back to fstatat in that case. Oh well!

Try this which forces the fallback to fstatat on Android

[v1.63.0-beta.7046.2da187b87.fix-7006-android-metadata](https://beta.rclone.org/branch/fix-7006-android-metadata/v1.63.0-beta.7046.2da187b87.fix-7006-android-metadata/) on branch [fix-7006-android-metadata](https://github.com/rclone/rclone/tree/fix-7006-android-metadata) (uploaded in 15-30 mins)

**Comment by iikira** [comment]
I tested the new branch, no errors anymore, thanks.
