### ISSUE TITLE
v1.67 crashes on OpenWRT (mipsle)

### ISSUE THREAD

**Issue by Kabachek** [rclone/rclone#7914]
Hi!
This is my router config:
`# about
{
        "kernel": "5.10.201",
        "hostname": "bukhara",
        "system": "MediaTek MT7621 ver:1 eco:3",
        "model": "Xiaomi Mi Router 3 Pro",
        "board_name": "xiaomi,mi-router-3-pro",
        "rootfs_type": "squashfs",
        "release": {
                "distribution": "OpenWrt",
                "version": "22.03.6",
                "revision": "r20265-f85a79bcb4",
                "target": "ramips/mt7621",
                "description": "OpenWrt 22.03.6 r20265-f85a79bcb4"
        }
`
Once day i have a this message in router's logfile:
`2024/06/14 22:25:21 NOTICE: Successfully updated rclone from version v1.66.0 to version v1.67.0
panic: DIRECT (8000) overlaps with LARGEFILE (8000)

goroutine 1 [running]:
github.com/hanwen/go-fuse/v2/fuse.(*flagNames).set(0x4de0d88, 0x8000, {0x24630fc, 0x6})
        github.com/hanwen/go-fuse/v2@v2.5.1/fuse/print.go:118 +0x258
github.com/hanwen/go-fuse/v2/fuse.init.2()
        github.com/hanwen/go-fuse/v2@v2.5.1/fuse/print_linux.go:13 +0x64`

v1.67 rclone crashes with any command
I'm tried latest BETA with the same result:
`# wget https://beta.rclone.org/rclone-beta-latest-linux-mipsle.zip
# ./rclone version
panic: DIRECT (8000) overlaps with LARGEFILE (8000)

goroutine 1 [running]:
github.com/hanwen/go-fuse/v2/fuse.(*flagNames).set(0x60db688, 0x8000, {0x24630bc,0x6})
        github.com/hanwen/go-fuse/v2@v2.5.1/fuse/print.go:118 +0x258
github.com/hanwen/go-fuse/v2/fuse.init.2()
        github.com/hanwen/go-fuse/v2@v2.5.1/fuse/print_linux.go:13 +0x64`

So, this time i'm downgraded to v1.66 (it's work fine) and turned selfupdate in my cron off

**Comment by ncw** [comment]
This is the upstream issue https://github.com/hanwen/go-fuse/issues/514

Note that I reported a bug about this before which was fixed https://github.com/hanwen/go-fuse/issues/502 but it looks like mipsle is affected too.

If you want to compile your own rclone then you can disable the `mount2` command like this

```diff
diff --git a/cmd/all/all.go b/cmd/all/all.go
index 37b15c5c3..6b8b989ed 100644
--- a/cmd/all/all.go
+++ b/cmd/all/all.go
@@ -37,7 +37,8 @@ import (
 	_ "github.com/rclone/rclone/cmd/md5sum"
 	_ "github.com/rclone/rclone/cmd/mkdir"
 	_ "github.com/rclone/rclone/cmd/mount"
-	_ "github.com/rclone/rclone/cmd/mount2"
+	// _ "github.com/rclone/rclone/cmd/mount2"
 	_ "github.com/rclone/rclone/cmd/move"
 	_ "github.com/rclone/rclone/cmd/moveto"
 	_ "github.com/rclone/rclone/cmd/ncdu"
```

I could potentially disable mount2 for mips entirely for a point release.
