### ISSUE TITLE
segfault when downloading native document file from ProtonDrive

### ISSUE THREAD

**Issue by navysky12** [rclone/rclone#7959]
#### The associated forum post URL from `https://forum.rclone.org`

None, was able to replicate consistently and assumed the segfault meant it should be directed here.

#### What is the problem you are having with rclone?

When trying to copy/sync files from the remote to local, if the file is a "document" file as made/edited through ProtonDrive's new native document functionality, a segfault occurs.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.67.0
- os/version: almalinux 9.4 (64 bit)
- os/kernel: 6.6.38 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.4
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

AlmaLinux 64 bit, Kernel Linux 6.6.38

#### Which cloud storage system are you using? (e.g. Google Drive)

ProtonDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone copy -vv --metadata --update "proton:" "/home/user/foo"`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2024/07/18 16:36:04 DEBUG : rclone: Version "v1.67.0" starting with parameters ["rclone" "copy" "-vv" "--metadata" "--update" "proton:" "/home/user/foo"]
2024/07/18 16:36:04 DEBUG : Creating backend with remote "proton:"
2024/07/18 16:36:04 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2024/07/18 16:36:04 DEBUG : proton drive root link ID '': Has cached credentials
2024/07/18 16:36:07 DEBUG : proton drive root link ID '': Used cached credential to initialize the ProtonDrive API
2024/07/18 16:36:07 DEBUG : Creating backend with remote "/home/user/foo"
2024/07/18 16:36:12 DEBUG : docfile: Original file size missing
2024/07/18 16:36:12 DEBUG : docfile: Need to transfer - File not found at Destination
2024/07/18 16:36:12 DEBUG : docfile: Original file size missing
2024/07/18 16:36:12 DEBUG : pkglist.txt: Sizes identical
2024/07/18 16:36:12 DEBUG : pkglist.txt: Destination mod time is within 1s of source and files identical, skipping
2024/07/18 16:36:12 DEBUG : docfile: Original file size missing
2024/07/18 16:36:12 DEBUG : docfile: Original file size missing
2024/07/18 16:36:12 DEBUG : test: Sizes identical
2024/07/18 16:36:12 DEBUG : Local file system at /home/user/foo: Waiting for checks to finish
2024/07/18 16:36:12 DEBUG : test: Destination mod time is within 1s of source and files identical, skipping
2024/07/18 16:36:12 DEBUG : Local file system at /home/user/foo: Waiting for transfers to finish
2024/07/18 16:36:12 DEBUG : docfile: Original file size missing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x162a8c6]

goroutine 89 [running]:
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc0007c88c0, {0x2b90450, 0xc0007fcbe0}, {0xc000abd170, 0x1, 0x20?})
        github.com/rclone/rclone/backend/protondrive/protondrive.go:886 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc000233260)
        github.com/rclone/rclone/fs/operations/reopen.go:147 +0x106
github.com/rclone/rclone/fs/operations.NewReOpen({0x2b90450, 0xc0007fcbe0}, {0x2ba69d0, 0xc0007c88c0}, 0xa, {0xc000abd140, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/reopen.go:102 +0x50b
github.com/rclone/rclone/fs/operations.Open({0x2b90450, 0xc0007fcbe0}, {0x2ba69d0, 0xc0007c88c0}, {0xc000abd140, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc000c97050, {0x2b90450, 0xc0007fcbe0})
        github.com/rclone/rclone/fs/operations/copy.go:257 +0x4e5
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc000c97050, {0x2b90450, 0xc0007fcbe0})
        github.com/rclone/rclone/fs/operations/copy.go:306 +0x16c
github.com/rclone/rclone/fs/operations.Copy({0x2b90450, 0xc0007fcbe0}, {0x2ba5f50, 0xc0010214a0}, {0x0, 0x0}, {0xc000948178, 0x8}, {0x2ba69d0, 0xc0007c88c0})
        github.com/rclone/rclone/fs/operations/copy.go:408 +0x485
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00075ac88, {0x2b90450, 0xc0007fcbe0}, 0xc0007fcb40, {0x2ba5f50, 0xc0010214a0}, 0x32, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:501 +0x205
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:531 +0x6b
```
docfile is the document file created natively in ProtonDrive.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
It looks like native docs don't have a size - try this

[v1.68.0-beta.8105.800ebb648.fix-7959-protondrive](https://beta.rclone.org/branch/fix-7959-protondrive/v1.68.0-beta.8105.800ebb648.fix-7959-protondrive/) on branch [fix-7959-protondrive](https://github.com/rclone/rclone/tree/fix-7959-protondrive) (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Thanks for testing. Well the segfault moved into the protondrive library...

I think we need @henrybear327 to take a look at this.

**Comment by henrybear327** [comment]
> Thanks for testing. Well the segfault moved into the protondrive library...
> 
> I think we need @henrybear327 to take a look at this.

I will dig into this. Thanks for reporting! @navysky12 @ncw

**Comment by HyperDevil** [comment]
Hi, i got the same error. It seems it was a document created using the proton document editor. It had 33KB size in the web interface but 0 size in the CLI output. So it´s a file size issue. When deleting the file from proton, rclone was happy again.

**Comment by jessebs** [comment]
A work around that works for me - try the flag `--min-size 1b`.  This will skip files <1byte in size

**Comment by LundiNord** [comment]
hi, i get the same error when using Celeste UI: (also with a folder with a Proton Document inside)

```
<3>ERROR : privat/privat: error listing: directory not found
<3>ERROR : rc: "operations/list": error: error in ListJSON: directory not found
<3>ERROR : rc: "operations/copyfile": error: panic received: runtime error: invalid memory address or nil pointer dereference 
goroutine 99 [running, locked to thread]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:26 +0x5e
github.com/rclone/rclone/fs/rc/jobs.(*Job).run.func1()
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/rc/jobs/job.go:109 +0x3d
panic({0x5e5f1c2d89c0?, 0x5e5f1da2e2a0?})
        /usr/lib/go/src/runtime/panic.go:785 +0x132
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc0008406e0, {0x5e5f1c705c48, 0xc000ad7170}, {0xc00041de70, 0x1, 0xc00041df80?})
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/backend/protondrive/protondrive.go:883 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc000a96780)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/reopen.go:116 +0x559
github.com/rclone/rclone/fs/operations.NewReOpen({0x5e5f1c705c48, 0xc000ad7170}, {0x5e5f1c719780, 0xc0008406e0}, 0xa, {0xc00041de60, 0x1, 0x1})
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/reopen.go:49 +0x167
github.com/rclone/rclone/fs/operations.Open({0x5e5f1c705c48, 0xc000ad7170}, {0x5e5f1c719780, 0xc0008406e0}, {0xc00041de60, 0x1, 0x1})
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/reopen.go:71 +0x68
github.com/rclone/rclone/fs/operations.Copy({0x5e5f1c705c48, 0xc000ad7170}, {0x5e5f1c718d00, 0xc00074b720}, {0x0, 0x0}, {0xc000770570, 0x17}, {0x5e5f1c719780, 0xc0008406e0})
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/operations.go:446 +0xe33
github.com/rclone/rclone/fs/operations.moveOrCopyFile({0x5e5f1c705c48, 0xc000ad7170}, {0x5e5f1c718d00, 0xc00074b720}, {0x5e5f1c719710, 0xc000890420}, {0xc000770570, 0x17}, {0xc0007e0c56, 0xa}, ...)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/operations.go:2058 +0xad6
github.com/rclone/rclone/fs/operations.rcMoveOrCopyFile({0x5e5f1c705c48, 0xc000ad7170}, 0xc000ad7110, 0x1)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/rc.go:194 +0xff
github.com/rclone/rclone/fs/operations.init.3.func1({0x5e5f1c705c48?, 0xc000ad7170?}, 0xc000b61b68?)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/operations/rc.go:170 +0x25
github.com/rclone/rclone/fs/rc/jobs.(*Job).run(0xc000890160, {0x5e5f1c705c48?, 0xc000ad7170?}, 0x5e5f1dbd7040?, 0x5e5f1c40bfe0?)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/rc/jobs/job.go:112 +0x5f
github.com/rclone/rclone/fs/rc/jobs.(*Jobs).NewJob(0x5e5f1da52740, {0x5e5f1c705ba0, 0x5e5f1dbd7040}, 0xc0007a1340, 0xc000ad70e0)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/rc/jobs/job.go:316 +0x62f
github.com/rclone/rclone/fs/rc/jobs.NewJob(...)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/fs/rc/jobs/job.go:326
github.com/rclone/rclone/librclone/librclone.RPC({0xc000770558, 0x13}, {0xc000b26f00, 0x5e})
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/librclone/librclone/librclone.go:117 +0x37c
main.RcloneRPC(0x763528001260?, 0x5e5f2dc43650)
        /home/alpaka/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/librclone-sys-0.6.3+rclone-v1.64.2/vendor/github.com/rclone/rclone/librclone/librclone.go:85 +0x49

```

**Comment by behrangsa** [comment]
I tried both of `rclone v1.69.1` and `rclone v1.71.0` and I get similar panics:

## rclone v1.69.1

```bash
$ rclone --version
rclone v1.69.1
- os/version: nixos 25.05 (64 bit)
- os/kernel: 6.16.6 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.24.6
- go/linking: dynamic
- go/tags: cmount

rclone copy OldProtonDrive: . --no-traverse
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29cb746]

goroutine 82 [running]:
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc0007fdea0, {0x3e3b470, 0xc0008a8780}, {0xc000ab4160, 0x1, 0xc0004c02a0?})
	github.com/rclone/rclone/backend/protondrive/protondrive.go:877 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc000fc2380)
	github.com/rclone/rclone/fs/operations/reopen.go:147 +0x109
github.com/rclone/rclone/fs/operations.NewReOpen({0x3e3b470, 0xc0008a8780}, {0x3e53c30, 0xc0007fdea0}, 0xa, {0xc000ab4150, 0x1, 0x1})
	github.com/rclone/rclone/fs/operations/reopen.go:102 +0x4f5
github.com/rclone/rclone/fs/operations.Open({0x3e3b470, 0xc0008a8780}, {0x3e53c30, 0xc0007fdea0}, {0xc000ab4150, 0x1, 0x1})
	github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc0007fb170, {0x3e3b470, 0xc0008a8780})
	github.com/rclone/rclone/fs/operations/copy.go:261 +0x4dc
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc0007fb170, {0x3e3b470, 0xc0008a8780})
	github.com/rclone/rclone/fs/operations/copy.go:310 +0x170
github.com/rclone/rclone/fs/operations.Copy({0x3e3b470, 0xc0008a8780}, {0x3e530d0, 0xc000610d20}, {0x0, 0x0}, {0xc0006818c0, 0xb}, {0x3e53c30, 0xc0007fdea0})
	github.com/rclone/rclone/fs/operations/copy.go:412 +0x473
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc0009e2288, {0x3e3b470, 0xc0008a8780}, 0xc0008a86e0, {0x3e530d0, 0xc000610d20}, 0x4b, 0x5778492b4e39316b?)
	github.com/rclone/rclone/fs/sync/sync.go:501 +0x1fe
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
	github.com/rclone/rclone/fs/sync/sync.go:531 +0x6b
```

## rclone v1.71.0

```bash
$ rclone --version
rclone v1.71.0
- os/version: nixos 25.05 (64 bit)
- os/kernel: 6.16.6 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.25.0
- go/linking: dynamic
- go/tags: cmount

$ rclone copy OldProtonDrive: .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c8bc86]

goroutine 111 [running]:
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc000ccc460, {0x430dea0, 0xc00045f770}, {0xc0003cefa0, 0x1, 0xc0007040c0?})
	github.com/rclone/rclone/backend/protondrive/protondrive.go:877 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc000000460)
	github.com/rclone/rclone/fs/operations/reopen.go:147 +0x109
github.com/rclone/rclone/fs/operations.NewReOpen({0x430dea0, 0xc00045f770}, {0x4328810, 0xc000ccc460}, 0xa, {0xc0003cef90, 0x1, 0x1})
	github.com/rclone/rclone/fs/operations/reopen.go:102 +0x4ff
github.com/rclone/rclone/fs/operations.Open({0x430dea0, 0xc00045f770}, {0x4328810, 0xc000ccc460}, {0xc0003cef90, 0x1, 0x1})
	github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc000abe360, {0x430dea0, 0xc00045f770})
	github.com/rclone/rclone/fs/operations/copy.go:262 +0x4da
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc000abe360, {0x430dea0, 0xc00045f770})
	github.com/rclone/rclone/fs/operations/copy.go:311 +0x170
github.com/rclone/rclone/fs/operations.Copy({0x430dea0, 0xc00045f770}, {0x4327cb0, 0xc000798840}, {0x0, 0x0}, {0xc000420fb0, 0xb}, {0x4328810, 0xc000ccc460})
	github.com/rclone/rclone/fs/operations/copy.go:413 +0x4dc
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000a48288, {0x430dea0, 0xc00045f770}, 0xc00045f6d0, {0x4327cb0, 0xc000798840}, 0x32, 0x0?)
	github.com/rclone/rclone/fs/sync/sync.go:505 +0x1fe
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
	github.com/rclone/rclone/fs/sync/sync.go:535 +0x7d
```

My rclone config is very basic:
```conf
$ cat ~/.config/rclone/rclone.conf 
[OldProtonDrive]
type = protondrive
username = ...
password = ...
2fa = ...
client_uid = ...
client_access_token = ...
client_refresh_token = ...
client_salted_key_pass = ...
```

My goal was to download all my files from Proton Drive and close my account, as due to some technical issues I couldn't downgrade my existing subscription from Visionary to something more affordable such as Proton Unlimited.

---

## Potential Workaround

If you want to do something similar, mount your Proton Drive and then copy all the files from your mount to your target directory:

In one shell run:
```bash
rclone mount YourProtonDrive: path/to/mount-dir --vfs-cache-mode full
```

In another shell run:
```bash
cp -fr path/to/mount-dir path/to/backup-dir
```
