### ISSUE TITLE
Git-Annex Clone to Dropbox Fails

### ISSUE THREAD

**Issue by Servinjesus1** [rclone/rclone#8068]
`batcher is shutting down`: git annex fails to upload large file to Dropbox.

<details><summary> Git-Annex Log </summary>

```
[2024-09-11 10:09:54.703477] (Utility.Process) process [54139] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2024-09-11 10:09:54.713334] (Utility.Process) process [54139] done ExitSuccess
[2024-09-11 10:09:54.713787] (Utility.Process) process [54143] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2024-09-11 10:09:54.7182] (Utility.Process) process [54143] done ExitSuccess
[2024-09-11 10:09:54.719259] (Utility.Process) process [54147] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2024-09-11 10:09:54.724725] (Utility.Process) process [54151] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","ls-files","--stage","-z","--error-unmatch","--","Ortec.h5"]
[2024-09-11 10:09:54.725099] (Utility.Process) process [54155] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2024-09-11 10:09:54.725486] (Utility.Process) process [54159] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2024-09-11 10:09:54.726063] (Utility.Process) process [54147] done ExitSuccess
[2024-09-11 10:09:54.726519] (Utility.Process) process [54163] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
copy Ortec.h5 [2024-09-11 10:09:54.731035] (Utility.Process) process [54164] chat: /opt/homebrew/bin/rclone ["gitannex"]
[2024-09-11 10:09:54.795657] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> VERSION 1
[2024-09-11 10:09:54.795769] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- EXTENSIONS INFO GETGITREMOTENAME UNAVAILABLERESPONSE ASYNC
[2024-09-11 10:09:54.795848] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> EXTENSIONS
[2024-09-11 10:09:54.795872] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- PREPARE
[2024-09-11 10:09:54.795929] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> GETCONFIG rcloneremotename
[2024-09-11 10:09:54.795959] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- VALUE dropbox
[2024-09-11 10:09:54.796007] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> GETCONFIG rcloneprefix
[2024-09-11 10:09:54.796055] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- VALUE <path/on/Dropbox>
[2024-09-11 10:09:54.796104] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> GETCONFIG rclonelayout
[2024-09-11 10:09:54.796123] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- VALUE nodir
[2024-09-11 10:09:54.796163] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> PREPARE-SUCCESS
[2024-09-11 10:09:54.796184] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- CHECKPRESENT MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5
[2024-09-11 10:09:55.603728] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> CHECKPRESENT-FAILURE MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5
[2024-09-11 10:09:55.604607] (Utility.Process) process [54173] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
(to dropbox...) [2024-09-11 10:09:55.611703] (Utility.Process) process [54177] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","write-tree"]
[2024-09-11 10:09:55.615612] (Utility.Process) process [54177] done ExitSuccess
[2024-09-11 10:09:55.615944] (Utility.Process) process [54181] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/annex/last-index"]
[2024-09-11 10:09:55.620188] (Utility.Process) process [54181] done ExitSuccess

[2024-09-11 10:09:55.62041] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- TRANSFER STORE MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5 .git/annex/objects/11/F3/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5
2024/09/11 10:20:47 ERROR : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Failed to copy: upload failed: batcher is shutting down
[2024-09-11 10:20:47.458215] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] --> TRANSFER-FAILURE STORE MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5 failed to copy file: upload failed: batcher is shutting down

  failed to copy file: upload failed: batcher is shutting down
failed
[2024-09-11 10:20:47.460153] (Utility.Process) process [54163] done ExitSuccess
[2024-09-11 10:20:47.460202] (Utility.Process) process [54159] done ExitSuccess
[2024-09-11 10:20:47.46022] (Utility.Process) process [54155] done ExitSuccess
[2024-09-11 10:20:47.460233] (Utility.Process) process [54151] done ExitSuccess
panic: upload failed: batcher is shutting down

goroutine 1 [running]:
github.com/rclone/rclone/cmd/gitannex.init.func1(0x140009f4500?, {0x105e6d668?, 0x4?, 0x103a5c70b?})
        github.com/rclone/rclone/cmd/gitannex/gitannex.go:610 +0x210
github.com/spf13/cobra.(*Command).execute(0x105c5c340, {0x105e6d668, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x105c544c0)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/rclone/rclone/cmd.Main()
        github.com/rclone/rclone/cmd/cmd.go:568 +0x34
main.main()
        github.com/rclone/rclone/rclone.go:14 +0x1c
[2024-09-11 10:20:47.463611] (Utility.Process) process [54164] done ExitFailure 2
[2024-09-11 10:20:47.464043] (Utility.Process) process [54173] done ExitSuccess
copy: 1 failed
```

</details>

Upload worked manually, so I wonder if there's an issue with the annex handler timing out. I'm not sure how to extract this debug info though since it's git annex calling rclone internally. If it helps, here's at least the verbose log of it succeeding.

<details>
<summary> Rclone directly </summary>

```
2024/09/11 11:15:46 DEBUG : rclone: Version "v1.67.0" starting with parameters ["rclone" "copy" ".git/annex/objects/11/F3/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5" "dropbox:1-Work/Annexes/.BeEST.220610-32Al70_7Be" "-vv"]
2024/09/11 11:15:46 DEBUG : Creating backend with remote ".git/annex/objects/11/F3/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5"
2024/09/11 11:15:46 DEBUG : Using config file from "/Users/coesite/.config/rclone/rclone.conf"
2024/09/11 11:15:46 DEBUG : fs cache: adding new entry for parent of ".git/annex/objects/11/F3/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5", "<path/to/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5"
2024/09/11 11:15:46 DEBUG : Creating backend with remote "dropbox:<path/on/Dropbox>"
2024/09/11 11:15:46 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Need to transfer - File not found at Destination
2024/09/11 11:15:47 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 1/32
2024/09/11 11:16:07 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 2/32
2024/09/11 11:16:28 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 3/32
2024/09/11 11:16:46 INFO  :
Transferred:      284.715 MiB / 3.072 GiB, 9%, 4.531 MiB/s, ETA 10m31s
Transferred:            0 / 1, 0%
Elapsed time:       1m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5:  9% /3.072Gi, 4.531Mi/s, 10m31s

2024/09/11 11:16:50 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 4/32
2024/09/11 11:17:11 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 5/32
2024/09/11 11:17:31 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 6/32
2024/09/11 11:17:46 INFO  :
Transferred:      578.027 MiB / 3.072 GiB, 18%, 4.897 MiB/s, ETA 8m44s
Transferred:            0 / 1, 0%
Elapsed time:       2m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 18% /3.072Gi, 4.897Mi/s, 8m44s

2024/09/11 11:17:52 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 7/32
2024/09/11 11:18:12 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 8/32
2024/09/11 11:18:33 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 9/32
2024/09/11 11:18:46 INFO  :
Transferred:      870.027 MiB / 3.072 GiB, 28%, 4.975 MiB/s, ETA 7m37s
Transferred:            0 / 1, 0%
Elapsed time:       3m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 27% /3.072Gi, 4.975Mi/s, 7m37s

2024/09/11 11:18:53 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 10/32
2024/09/11 11:19:14 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 11/32
2024/09/11 11:19:35 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 12/32
2024/09/11 11:19:46 INFO  :
Transferred:        1.133 GiB / 3.072 GiB, 37%, 4.874 MiB/s, ETA 6m47s
Transferred:            0 / 1, 0%
Elapsed time:       4m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 36% /3.072Gi, 4.874Mi/s, 6m47s

2024/09/11 11:19:55 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 13/32
2024/09/11 11:20:16 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 14/32
2024/09/11 11:20:36 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 15/32
2024/09/11 11:20:46 INFO  :
Transferred:        1.416 GiB / 3.072 GiB, 46%, 4.829 MiB/s, ETA 5m51s
Transferred:            0 / 1, 0%
Elapsed time:       5m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 46% /3.072Gi, 4.829Mi/s, 5m51s

2024/09/11 11:20:57 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 16/32
2024/09/11 11:21:18 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 17/32
2024/09/11 11:21:38 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 18/32
2024/09/11 11:21:46 INFO  :
Transferred:        1.701 GiB / 3.072 GiB, 55%, 4.770 MiB/s, ETA 4m54s
Transferred:            0 / 1, 0%
Elapsed time:       6m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 55% /3.072Gi, 4.770Mi/s, 4m54s

2024/09/11 11:21:59 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 19/32
2024/09/11 11:22:20 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 20/32
2024/09/11 11:22:40 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 21/32
2024/09/11 11:22:46 INFO  :
Transferred:        1.984 GiB / 3.072 GiB, 65%, 4.804 MiB/s, ETA 3m51s
Transferred:            0 / 1, 0%
Elapsed time:       7m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 64% /3.072Gi, 4.804Mi/s, 3m51s

2024/09/11 11:23:01 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 22/32
2024/09/11 11:23:21 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 23/32
2024/09/11 11:23:42 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 24/32
2024/09/11 11:23:46 INFO  :
Transferred:        2.270 GiB / 3.072 GiB, 74%, 4.857 MiB/s, ETA 2m49s
Transferred:            0 / 1, 0%
Elapsed time:       8m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 73% /3.072Gi, 4.857Mi/s, 2m49s

2024/09/11 11:24:03 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 25/32
2024/09/11 11:24:24 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 26/32
2024/09/11 11:24:45 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 27/32
2024/09/11 11:24:46 INFO  :
Transferred:        2.549 GiB / 3.072 GiB, 83%, 4.761 MiB/s, ETA 1m52s
Transferred:            0 / 1, 0%
Elapsed time:       9m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 82% /3.072Gi, 4.761Mi/s, 1m52s

2024/09/11 11:25:05 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 28/32
2024/09/11 11:25:26 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 29/32
2024/09/11 11:25:46 INFO  :
Transferred:        2.832 GiB / 3.072 GiB, 92%, 4.925 MiB/s, ETA 49s
Transferred:            0 / 1, 0%
Elapsed time:      10m0.4s
Transferring:
 * MD5E-s3298430410--153e…eb1096927b04239896b.h5: 92% /3.072Gi, 4.925Mi/s, 49s

2024/09/11 11:25:46 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 30/32
2024/09/11 11:26:07 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 31/32
2024/09/11 11:26:28 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Uploading chunk 32/32
2024/09/11 11:26:37 DEBUG : Dropbox root '1-Work/Annexes/.BeEST.220610-32Al70_7Be': Adding "MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5" to batch
2024/09/11 11:26:38 DEBUG : Dropbox root '<path/on/Dropbox>': Batch idle for 500ms so committing
2024/09/11 11:26:38 DEBUG : Dropbox root '<path/on/Dropbox>': Committing sync batch length 1 starting with: MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5
2024/09/11 11:26:39 DEBUG : Dropbox root '<path/on/Dropbox>': Committed sync batch length 1 starting with: MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5
2024/09/11 11:26:39 DEBUG : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: dropbox = eaaf689557e6dec3b1aec92035ac5ab1e09e9546c736defff33810436e932b56 OK
2024/09/11 11:26:39 INFO  : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Copied (new)
2024/09/11 11:26:39 INFO  :
Transferred:        3.072 GiB / 3.072 GiB, 100%, 4.217 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:     10m52.9s

2024/09/11 11:26:39 DEBUG : 10 go routines active
2024/09/11 11:26:39 INFO  : Dropbox root '<path/on/Dropbox>': Committing uploads - please wait...
```

</details>

```
rclone v1.67.0
- os/version: darwin 14.6.1 (64 bit)
- os/kernel: 23.6.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.22.4
- go/linking: dynamic
- go/tags: none
```

---

<details><summary> <h3>GitHub User's Guide</h3> </summary>

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

</details>

**Comment by ncw** [comment]
Do you want to have a look at this @dmcardle ?

**Comment by dmcardle** [comment]
I'll take a look soon, probably tomorrow! Thank you for the bug report, @Servinjesus1!

**Comment by dmcardle** [comment]
(A few notes, but nothing substantial yet.)

It's somewhat suspicious to me how near to 10 minutes apart these lines are (although it's not a round number, more like 10 minutes and 52 seconds):

```
[2024-09-11 10:09:55.62041] (Annex.ExternalAddonProcess) /opt/homebrew/bin/rclone[1] <-- TRANSFER STORE MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5 .git/annex/objects/11/F3/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5/MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5
2024/09/11 10:20:47 ERROR : MD5E-s3298430410--153e20b421335eb1096927b04239896b.h5: Failed to copy: upload failed: batcher is shutting down
```

Under the assumption that the error was caused by a timeout, we should figure out who owns the timer: git-annex proper, rclone's gitannex command, some other part of rclone, or possibly even Dropbox's server.

It looks like "batcher is shutting down" must be generated when `Batcher` is shut down via its `b.closed` channel: https://github.com/rclone/rclone/blob/da70088b11e633999f2f920d3c603d97c292135e/lib/batcher/batcher.go#L263-L266

That channel is closed by `(b *Batcher[Item, Result]) Shutdown()`, which is registered as an atexit handler 🤔. If we believe the timeout hypothesis, it's plausible that git-annex sent the rclone subprocess a signal such as SIGTERM after ~10 minutes.

**Comment by dmcardle** [comment]
I took another look at this today, but spent all my time following a red herring. I nearly convinced myself that this was due to the `RCLONE_DROPBOX_BATCH_COMMIT_TIMEOUT` option, which defaults to 10 minutes, but then I realized that that the option is never used. So let's scratch that particular suspect off the list. Filed #8089.
