### ISSUE TITLE
iCloud sync SIGSEGV crash 

### ISSUE THREAD

**Issue by drbourbon** [rclone/rclone#8211]
#### What is the problem you are having with rclone?

SIGSEGV crash with iclouddrive backend. Tends to happen after many files (thousands) have been transferred.

#### What is your rclone version (output from `rclone version`)

rclone v1.69.0-beta.8419.ca8860177
- os/version: debian 12.8 (64 bit)
- os/kernel: 6.1.0-26-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.3
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian GNU/Linux 12

#### Which cloud storage system are you using? (e.g. Google Drive)

iclouddrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone sync icloud:/ Drive/ --log-level INFO --log-file=rclone.log --ignore-size --ignore-existing

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2024/11/26 17:41:57 INFO  : Code/web/deluge-cmd/node_modules/electron-installer-flatpak/node_modules/async/node_modules/lodash/fp/equals.js: Copied (new)
2024/11/26 17:41:58 INFO  : Code/web/deluge-cmd/node_modules/electron-installer-flatpak/node_modules/async/node_modules/lodash/fp/escapeRegExp.js: Copied (new)
2024/11/26 17:41:59 INFO  : Code/web/deluge-cmd/node_modules/electron-installer-flatpak/node_modules/async/node_modules/lodash/fp/extend.js: Copied (new)
2024/11/26 17:41:59 INFO  : Code/web/deluge-cmd/node_modules/electron-installer-flatpak/node_modules/async/node_modules/lodash/fp/every.js: Copied (new)
2024/11/26 17:41:59 INFO  : Code/web/deluge-cmd/node_modules/electron-installer-flatpak/node_modules/async/node_modules/lodash/fp/extendAll.js: Copied (new)
2024/11/26 17:41:59 INFO  : Code/web/deluge-cmd/node_modules/electron-installer-flatpak/node_modules/async/node_modules/lodash/fp/extendAllWith.js: Copied (new)
2024/11/26 17:42:05 INFO  : 
Transferred:        8.252 MiB / 269.576 MiB, 3%, 0 B/s, ETA -
Errors:                47 (retrying may help)
Checks:             54714 / 54714, 100%
Transferred:         2159 / 3170, 68%
Elapsed time:     17m59.9s
Transferring:
 * Code/web/deluge-cmd/no…odash/fp/extendWith.js: transferring
 * Code/web/deluge-cmd/no…ules/lodash/fp/fill.js: transferring
 * Code/web/deluge-cmd/no…es/lodash/fp/filter.js: transferring
 * Code/web/deluge-cmd/no…ules/lodash/fp/find.js: transferring

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1238cd2]

goroutine 73 [running]:
github.com/rclone/rclone/backend/iclouddrive/api.(*DriveService).DownloadFile(0xc000ba4cc0, {0x2b71100, 0xc000bd42d0}, {0xc00a12d8c0, 0x205}, {0xc00555b1a0, 0x1, 0x1})
        github.com/rclone/rclone/backend/iclouddrive/api/drive.go:257 +0x192
github.com/rclone/rclone/backend/iclouddrive.(*Object).Open.func1()
        github.com/rclone/rclone/backend/iclouddrive/iclouddrive.go:1024 +0xd1
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0xa, 0x50?)
        github.com/rclone/rclone/fs/pacer.go:88 +0x32
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0xc000bac120, 0xc001c49c20, 0xa)
        github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x7c
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0xc000bac120, 0xc001c49c20)
        github.com/rclone/rclone/lib/pacer/pacer.go:216 +0x92
github.com/rclone/rclone/backend/iclouddrive.(*Object).Open(0xc003fb3d60, {0x2b71100, 0xc000bd42d0}, {0xc00555b1a0, 0x1, 0x1})
        github.com/rclone/rclone/backend/iclouddrive/iclouddrive.go:1013 +0x1cd
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc00024afc0)
        github.com/rclone/rclone/fs/operations/reopen.go:147 +0x109
github.com/rclone/rclone/fs/operations.NewReOpen({0x2b71100, 0xc000bd42d0}, {0x2b87e40, 0xc003fb3d60}, 0xa, {0xc00555b180, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/reopen.go:102 +0x50b
github.com/rclone/rclone/fs/operations.Open({0x2b71100, 0xc000bd42d0}, {0x2b87e40, 0xc003fb3d60}, {0xc00555b180, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc005058bd0, {0x2b71100, 0xc000bd42d0})
        github.com/rclone/rclone/fs/operations/copy.go:261 +0x4dc
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc005058bd0, {0x2b71100, 0xc000bd42d0})
        github.com/rclone/rclone/fs/operations/copy.go:310 +0x176
github.com/rclone/rclone/fs/operations.Copy({0x2b71100, 0xc000bd42d0}, {0x2b88310, 0xc000bd8000}, {0x0, 0x0}, {0xc003a30000, 0x6d}, {0x2b87e40, 0xc003fb3d60})
        github.com/rclone/rclone/fs/operations/copy.go:412 +0x493
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc0001c4508, {0x2b71100, 0xc000bd42d0}, 0xc000bd4230, {0x2b88310, 0xc000bd8000}, 0x4b, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:501 +0x1fe
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:531 +0x6b

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by iclems** [comment]
Looking into it, I'm think this probably relates to how we use the return of srv.Call() 

Other services using REST pass both resp and err to a shouldRetry which actually checks for resp != nil

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/9b73fa56-0d4f-4f1c-a1f2-2c78ebf44498" />

**Comment by iclems** [comment]
Line 257 (per the trace): not impossible for err != nil but resp is. Not a Go expert, but will try to play with it later.

**Comment by iclems** [comment]
@lostb1t curious for your thoughts as it seems you're the original contributor (congrats!). As mentioned, I'm not the most familiar with Go but considering we are consistently experiencing SIGSEV on line 256 of drive.go I'm considering we should check for resp != nil as the underlying REST provider may not guarantee it

<img width="894" alt="Image" src="https://github.com/user-attachments/assets/d640a793-e26e-4040-b40e-79abb9e022b0" />

**Comment by iclems** [comment]
Issue solved. I also think that I potentially solved another potentially issue here. My understanding is that currently most files may end up being downloaded twice (lines 254 and 266), except when an error appears on 255. 

Will run a full sync tomorrow and open a pull request. Would love the OP review. 

<img width="731" alt="Image" src="https://github.com/user-attachments/assets/4fb88d3a-1721-4928-8c0b-793fd14bc5cf" />

**Comment by iclems** [comment]
FYI now that we are passing this error, here's what happens occasionally: 
Failed to copy: failed to open source object: RootURL not set

**Comment by prrar** [comment]
I also have this problem syncing thousands (20k+) files. Tested on Debian 12, Ubuntu Server 24.04 LTS, Ubuntu Server 25.04 and FreeBSD 14. All of them running rclone v1.69.2.

**Comment by ncw** [comment]
@prrar I merged a fix for this to master just now. Please give it 30 minutes then try [the latest beta](https://beta.rclone.org/)
 - thanks.

**Comment by prrar** [comment]
@ncw that worked fine, thank you very much! 200k files and no crashes.
