### ISSUE TITLE
`--gphotos-batch-mode async` error

### ISSUE THREAD

**Issue by dzg** [rclone/rclone#8233]
Trying `rclone copy` to a Google Photos remote using `--gphotos-batch-mode async` I keep getting this:

```
2024/12/02 20:13:29 DEBUG : Google Photos path "album/rclone": >Put:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc031f0]

goroutine 121 [running]:
github.com/rclone/rclone/backend/googlephotos.(*Object).setMetaData(...)
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:872
github.com/rclone/rclone/backend/googlephotos.(*Object).Update(0x4000574770, {0x240e410, 0x400081d720}, {0x23e74a0, 0x4000786300}, {0xf500ca40c4e8, 0x4000aa67c8}, {0x400057f4b0, 0x1, 0x1})
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:1148 +0x6d0
github.com/rclone/rclone/backend/googlephotos.(*Fs).Put(0x40003005b0, {0x240e410, 0x400081d720}, {0x23e74a0, 0x4000786300}, {0xf500ca40c4e8, 0x4000aa67c8}, {0x400057f4b0, 0x1, 0x1})
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:693 +0x148
github.com/rclone/rclone/fs/operations.(*copy).updateOrPut(0x400042d0e0, {0x240e410, 0x400081d720}, {0x23fa780?, 0x400058e000?}, {0x400057f4b0, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/copy.go:217 +0x1a4
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0x400042d0e0, {0x240e410, 0x400081d720})
        github.com/rclone/rclone/fs/operations/copy.go:270 +0x54c
github.com/rclone/rclone/fs/operations.(*copy).copy(0x400042d0e0, {0x240e410, 0x400081d720})
        github.com/rclone/rclone/fs/operations/copy.go:310 +0x108
github.com/rclone/rclone/fs/operations.Copy({0x240e410, 0x400081d720}, {0x2424ab0, 0x40003005b0}, {0x0, 0x0}, {0x4000de8e3d, 0x17}, {0x2424110, 0x4000aa67c8})
        github.com/rclone/rclone/fs/operations/copy.go:412 +0x394
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0x4000674788, {0x240e410, 0x400081d720}, 0x400081d680, {0x2424ab0, 0x40003005b0}, 0x32, 0x1?)
        github.com/rclone/rclone/fs/sync/sync.go:501 +0x160
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:531 +0x6c
```

```
$ rclone version
rclone v1.68.2
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.8.0-1015-oracle (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.23.3
- go/linking: static
- go/tags: none
```

 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by dzg** [comment]
FWIW, this is happening on latest beta too:

```
2024/12/11 11:22:13 INFO  : Starting transaction limiter: max 1 transactions/s with burst 1
2024/12/11 11:22:13 DEBUG : rclone: Version "v1.69.0-beta.8430.6a983d601" starting with parameters ["rclone" "copy" "-Pvv" "--transfers" "16" "--tpslimit" "1" "--drive-chunk-size" "128M" "--exclude" "*.{xml,bin,json,thm,DS_Store}*" "--ignore-case" "--log-file=rclone-photos-20241211_112213.log" "z00:Shelly_Z00/Shelly_NYU/Shelly Photos from NYU" "gpzs2:album/rclone" "--gphotos-read-size" "--gphotos-batch-mode" "async"]
...
2024/12/11 11:24:08 DEBUG : Google Photos path "album/rclone": Adding "to file/iPhoto export/IMG_1956.heic" to batch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc1b9a8]

goroutine 106 [running]:
github.com/rclone/rclone/backend/googlephotos.(*Object).setMetaData(...)
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:900
github.com/rclone/rclone/backend/googlephotos.(*Object).Update(0x4000638230, {0x2504cb0, 0x4000532370}, {0x24dd940, 0x4000633000}, {0x0?, 0x1c07040?}, {0x40015c62d0, 0x1, 0x1})
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:1180 +0x618
github.com/rclone/rclone/fs/operations.(*copy).updateOrPut(0x4000c40360, {0x2504cb0, 0x4000532370}, {0x24f0ba0?, 0x4000b9e380?}, {0x40015c62d0, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/copy.go:211 +0x144
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0x4000c40360, {0x2504cb0, 0x4000532370})
        github.com/rclone/rclone/fs/operations/copy.go:270 +0x54c
github.com/rclone/rclone/fs/operations.(*copy).copy(0x4000c40360, {0x2504cb0, 0x4000532370})
        github.com/rclone/rclone/fs/operations/copy.go:310 +0x108
github.com/rclone/rclone/fs/operations.Copy({0x2504cb0, 0x4000532370}, {0x251b910, 0x4000b122a0}, {0x251b980, 0x4000638230}, {0x40010e820d, 0x23}, {0x251af70, 0x4000c24df8})
        github.com/rclone/rclone/fs/operations/copy.go:412 +0x394
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0x40002e8f08, {0x2504cb0, 0x4000532370}, 0x40005322d0, {0x251b910, 0x4000b122a0}, 0x3e, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:501 +0x160
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:531 +0x6c
```

**Comment by dzg** [comment]
Also FWIW, using `--gphotos-batch-mode off` also causes panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc031f0]

goroutine 75 [running]:
github.com/rclone/rclone/backend/googlephotos.(*Object).setMetaData(...)
	github.com/rclone/rclone/backend/googlephotos/googlephotos.go:872
github.com/rclone/rclone/backend/googlephotos.(*Object).Update(0x400038f880, {0x240e410, 0x4000c8c690}, {0x23e74a0, 0x4000609100}, {0xf5d5a1c76fa8, 0x40009d0510}, {0x40009bd3e0, 0x1, 0x1})
	github.com/rclone/rclone/backend/googlephotos/googlephotos.go:1148 +0x6d0
github.com/rclone/rclone/backend/googlephotos.(*Fs).Put(0x4000a20d00, {0x240e410, 0x4000c8c690}, {0x23e74a0, 0x4000609100}, {0xf5d5a1c76fa8, 0x40009d0510}, {0x40009bd3e0, 0x1, 0x1})
	github.com/rclone/rclone/backend/googlephotos/googlephotos.go:693 +0x148
github.com/rclone/rclone/fs/operations.(*copy).updateOrPut(0x40007dd170, {0x240e410, 0x4000c8c690}, {0x23fa780?, 0x4000baa0e0?}, {0x40009bd3e0, 0x1, 0x1})
	github.com/rclone/rclone/fs/operations/copy.go:217 +0x1a4
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0x40007dd170, {0x240e410, 0x4000c8c690})
	github.com/rclone/rclone/fs/operations/copy.go:270 +0x54c
github.com/rclone/rclone/fs/operations.(*copy).copy(0x40007dd170, {0x240e410, 0x4000c8c690})
	github.com/rclone/rclone/fs/operations/copy.go:310 +0x108
github.com/rclone/rclone/fs/operations.Copy({0x240e410, 0x4000c8c690}, {0x2424ab0, 0x4000a20d00}, {0x0, 0x0}, {0x4000b616fd, 0x16}, {0x2424110, 0x40009d0510})
	github.com/rclone/rclone/fs/operations/copy.go:412 +0x394
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0x4000553b88, {0x240e410, 0x4000c8c690}, 0x4000c8c5f0, {0x2424ab0, 0x4000a20d00}, 0xc, 0x0?)
	github.com/rclone/rclone/fs/sync/sync.go:501 +0x160
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
	github.com/rclone/rclone/fs/sync/sync.go:531 +0x6c

```

**Comment by ncw** [comment]
There seems to be a pretty obvious cause for this!

Can you give this a try please?

[v1.69.0-beta.8454.51d162e58.fix-8233-gphotos-crash](https://beta.rclone.org/branch/fix-8233-gphotos-crash/v1.69.0-beta.8454.51d162e58.fix-8233-gphotos-crash/) on branch [fix-8233-gphotos-crash](https://github.com/rclone/rclone/tree/fix-8233-gphotos-crash) (uploaded in 15-30 mins)

**Comment by dzg** [comment]
Thanks, I will try!

Do you think this might help with https://forum.rclone.org/t/google-photos-upload-issue-2/49003 ?

I'm kind of at an impasse... should I post that issue here?

**Comment by dzg** [comment]
> Can you give this a try please?
> 
> [v1.69.0-beta.8454.51d162e58.fix-8233-gphotos-crash](https://beta.rclone.org/branch/fix-8233-gphotos-crash/v1.69.0-beta.8454.51d162e58.fix-8233-gphotos-crash/) on branch [fix-8233-gphotos-crash](https://github.com/rclone/rclone/tree/fix-8233-gphotos-crash) (uploaded in 15-30 mins)

\`\`\`  
$ rclone version  
rclone v1.69.0-beta.8456.27f448d14  
\- os/version: ubuntu 24.04 (64 bit)  
\- os/kernel: 6.8.0-1015-oracle (aarch64)  
\- os/type: linux  
\- os/arch: arm64 (ARMv8 compatible)  
\- go/version: go1.23.4  
\- go/linking: static  
\- go/tags: none  
\`\`\`

\`\`\`  
2024/12/13 11:03:19 DEBUG : Google Photos path "album/rclone": Adding "to file/MEDIA/C0360.MP4" to batch  
panic: runtime error: invalid memory address or nil pointer dereference  
\[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc0aa28\]

goroutine 95 \[running\]:  
github.com/rclone/rclone/backend/googlephotos.(\*Object).setMetaData(...)  
github.com/rclone/rclone/backend/googlephotos/googlephotos.go:900  
github.com/rclone/rclone/backend/googlephotos.(\*Object).Update(0x4000485420, {0x2501ad0, 0x4000c305a0}, {0x24da660, 0x4000719500}, {0x4000c305a0?, 0x4000ba79f8?}, {0x4000037980, 0x1, 0x1})  
github.com/rclone/rclone/backend/googlephotos/googlephotos.go:1180 +0x618  
github.com/rclone/rclone/backend/googlephotos.(\*Fs).Put(0x4000c5c380, {0x2501ad0, 0x4000c305a0}, {0x24da660, 0x4000719500}, {0xe960946fdc28, 0x4000c10c30}, {0x4000037980, 0x1, 0x1})  
github.com/rclone/rclone/backend/googlephotos/googlephotos.go:721 +0xc8  
github.com/rclone/rclone/fs/operations.(\*copy).updateOrPut(0x40002093b0, {0x2501ad0, 0x4000c305a0}, {0x24ed860?, 0x4000c5c000?}, {0x4000037980, 0x1, 0x1})  
github.com/rclone/rclone/fs/operations/copy.go:217 +0x1a4  
github.com/rclone/rclone/fs/operations.(\*copy).manualCopy(0x40002093b0, {0x2501ad0, 0x4000c305a0})  
github.com/rclone/rclone/fs/operations/copy.go:270 +0x54c  
github.com/rclone/rclone/fs/operations.(\*copy).copy(0x40002093b0, {0x2501ad0, 0x4000c305a0})  
github.com/rclone/rclone/fs/operations/copy.go:310 +0x108  
github.com/rclone/rclone/fs/operations.Copy({0x2501ad0, 0x4000c305a0}, {0x2518570, 0x4000c5c380}, {0x0, 0x0}, {0x4000e8a25d, 0x17}, {0x2517bd0, 0x4000c10c30})  
github.com/rclone/rclone/fs/operations/copy.go:412 +0x394  
github.com/rclone/rclone/fs/sync.(\*syncCopyMove).pairCopyOrMove(0x40004c6c88, {0x2501ad0, 0x4000c305a0}, 0x4000c30500, {0x2518570, 0x4000c5c380}, 0x3, 0x7acb2cb2cb2cb2cb?)  
github.com/rclone/rclone/fs/sync/sync.go:501 +0x160  
created by github.com/rclone/rclone/fs/sync.(\*syncCopyMove).startTransfers in goroutine 1  
github.com/rclone/rclone/fs/sync/sync.go:531 +0x6c  
\`\`\`

**Comment by dzg** [comment]
> Can you give this a try please?
> 
> [v1.69.0-beta.8454.51d162e58.fix-8233-gphotos-crash](https://beta.rclone.org/branch/fix-8233-gphotos-crash/v1.69.0-beta.8454.51d162e58.fix-8233-gphotos-crash/) on branch [fix-8233-gphotos-crash](https://github.com/rclone/rclone/tree/fix-8233-gphotos-crash) (uploaded in 15-30 mins)

\`\`\`  
$ rclone version  
rclone v1.69.0-beta.8456.27f448d14  
\- os/version: ubuntu 24.04 (64 bit)  
\- os/kernel: 6.8.0-1015-oracle (aarch64)  
\- os/type: linux  
\- os/arch: arm64 (ARMv8 compatible)  
\- go/version: go1.23.4  
\- go/linking: static  
\- go/tags: none  
\`\`\`

\`\`\`  
2024/12/13 11:03:19 DEBUG : Google Photos path "album/rclone": Adding "to file/MEDIA/C0360.MP4" to batch  
panic: runtime error: invalid memory address or nil pointer dereference  
\[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc0aa28\]

goroutine 95 \[running\]:  
github.com/rclone/rclone/backend/googlephotos.(\*Object).setMetaData(...)  
github.com/rclone/rclone/backend/googlephotos/googlephotos.go:900  
github.com/rclone/rclone/backend/googlephotos.(\*Object).Update(0x4000485420, {0x2501ad0, 0x4000c305a0}, {0x24da660, 0x4000719500}, {0x4000c305a0?, 0x4000ba79f8?}, {0x4000037980, 0x1, 0x1})  
github.com/rclone/rclone/backend/googlephotos/googlephotos.go:1180 +0x618  
github.com/rclone/rclone/backend/googlephotos.(\*Fs).Put(0x4000c5c380, {0x2501ad0, 0x4000c305a0}, {0x24da660, 0x4000719500}, {0xe960946fdc28, 0x4000c10c30}, {0x4000037980, 0x1, 0x1})  
github.com/rclone/rclone/backend/googlephotos/googlephotos.go:721 +0xc8  
github.com/rclone/rclone/fs/operations.(\*copy).updateOrPut(0x40002093b0, {0x2501ad0, 0x4000c305a0}, {0x24ed860?, 0x4000c5c000?}, {0x4000037980, 0x1, 0x1})  
github.com/rclone/rclone/fs/operations/copy.go:217 +0x1a4  
github.com/rclone/rclone/fs/operations.(\*copy).manualCopy(0x40002093b0, {0x2501ad0, 0x4000c305a0})  
github.com/rclone/rclone/fs/operations/copy.go:270 +0x54c  
github.com/rclone/rclone/fs/operations.(\*copy).copy(0x40002093b0, {0x2501ad0, 0x4000c305a0})  
github.com/rclone/rclone/fs/operations/copy.go:310 +0x108  
github.com/rclone/rclone/fs/operations.Copy({0x2501ad0, 0x4000c305a0}, {0x2518570, 0x4000c5c380}, {0x0, 0x0}, {0x4000e8a25d, 0x17}, {0x2517bd0, 0x4000c10c30})  
github.com/rclone/rclone/fs/operations/copy.go:412 +0x394  
github.com/rclone/rclone/fs/sync.(\*syncCopyMove).pairCopyOrMove(0x40004c6c88, {0x2501ad0, 0x4000c305a0}, 0x4000c30500, {0x2518570, 0x4000c5c380}, 0x3, 0x7acb2cb2cb2cb2cb?)  
github.com/rclone/rclone/fs/sync/sync.go:501 +0x160  
created by github.com/rclone/rclone/fs/sync.(\*syncCopyMove).startTransfers in goroutine 1  
github.com/rclone/rclone/fs/sync/sync.go:531 +0x6c  
\`\`\`

**Comment by ncw** [comment]
I need a way to replicate this I think.

Can you provide the full command line for your rclone and the output of `rclone config redacted` plus some idea of how to replicate - thank you :-)

**Comment by dzg** [comment]
```
$ rclone config redacted
[Shelly]
type = drive
scope = drive
service_account_file = /home/ubuntu/immich-oracle@rc2024-428206.iam.gserviceaccount.com.json
team_drive = XXX

[gd0]
type = drive
skip_shortcuts = true
scope = drive
token = XXX
team_drive =

[z00]
type = combine
upstreams = "Shelly=Shelly:" "MyDrive=gd0:"

[gpzs2]
type = google photos
client_id = XXX
client_secret = XXX
token = XXX
```

 ```
./rclone-test copy -Pvv \
 "z00:Shelly/Shelly_NYU/Shelly Photos from NYU" "gpzs2:album/rclone" \
 --transfers 32 \
 --tpslimit 1 \
 --drive-chunk-size 128M \
 --exclude "*.{xml,bin,json,thm,DS_Store}*" \
 --ignore-case \
 --log-file=rclone-photos-"$(date +%Y%m%d_%H%M%S).log" \
 --gphotos-batch-size 32 \
 --gphotos-batch-mode async
```

 LMK if I can help any other way! THanks

**Comment by ncw** [comment]
It would be really helpful if you could attach a log file of it going wrong with -vv --dump responses

That will have names of pictures and albums in so if you don't want to make them public you can email the log (or a link to the log) to nick@craig-wood.com

Thank you

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.69

**Comment by dequis** [comment]
Hello, I am getting an identical traceback with rclone `v1.70.0-beta.8745.15510c66d` and current git master.

No special options besides `--gphotos-batch-mode async`, crashes shortly after the first file. I reduced transfers to 1 because that's enough.

```
rclone copy ./ gphotos:album/[...]/ -P --exclude '*.xmp' --gphotos-batch-mode async --transfers 1
```

Traceback:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11ae036]

goroutine 87 [running]:
github.com/rclone/rclone/backend/googlephotos.(*Object).setMetaData(...)
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:913
github.com/rclone/rclone/backend/googlephotos.(*Object).Update(0xc0004857a0, {0x2e6b2e0, 0xc00053a140}, {0x2e42160, 0xc0011ba100}, {0x28eaf80?, 0x207301?}, {0xc000abe240, 0x1, 0x1})
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:1196 +0x776
github.com/rclone/rclone/backend/googlephotos.(*Fs).Put(0xc000000380, {0x2e6b2e0, 0xc00053a140}, {0x2e42160, 0xc0011ba100}, {0x78d7f2cf69c0, 0xc001520180}, {0xc000abe240, 0x1, 0x1})
        github.com/rclone/rclone/backend/googlephotos/googlephotos.go:734 +0x108
github.com/rclone/rclone/fs/operations.(*copy).updateOrPut(0xc000abd8c0, {0x2e6b2e0, 0xc00053a140}, {0x2e55e78?, 0xc00118e0e0?}, {0xc000abe240, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/copy.go:217 +0x225
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc000abd8c0, {0x2e6b2e0, 0xc00053a140})
        github.com/rclone/rclone/fs/operations/copy.go:270 +0x6d8
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc000abd8c0, {0x2e6b2e0, 0xc00053a140})
        github.com/rclone/rclone/fs/operations/copy.go:310 +0x170
github.com/rclone/rclone/fs/operations.Copy({0x2e6b2e0, 0xc00053a140}, {0x2e82fb0, 0xc000000380}, {0x0, 0x0}, {0xc00172c9c0, 0x15}, {0x2e839c0, 0xc001520180})
        github.com/rclone/rclone/fs/operations/copy.go:412 +0x473
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00091e008, {0x2e6b2e0, 0xc00053a140}, 0xc00053a0a0, {0x2e82fb0, 0xc000000380}, 0x9, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:502 +0x1fe
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:532 +0x7d
```

I did some debugging. The context of the calling function:

https://github.com/rclone/rclone/blob/15510c66d401e6737a2b15a0dba988e04ffb4ddd/backend/googlephotos/googlephotos.go#L1180-L1196

The first branch of the if is taken, when `o.fs.batcher.Batching()`. The second branch (which the bugfix is about) is not involved here as far as i can tell.

`o.fs.batcher.Commit()` returns nil info and nil err, from here:

https://github.com/rclone/rclone/blob/15510c66d401e6737a2b15a0dba988e04ffb4ddd/lib/batcher/batcher.go#L276-L278

The comment on that function also specifies it always returns nil info on async mode.

So as long as `setMetaData` is called and can't take nils, the `o.fs.batcher.Batching()` branch will always crash this in async mode.

I don't really understand much beyond this. Sounds like we have no way to set metadata in async mode. No idea how bad that is.

**Comment by dequis** [comment]
Yeah I think this fixes the bug. I'm not super experienced with google photos and its weirdnesses (it's only been three days of trying to upload stuff) and in the beginning I felt like I got more i/o errors in this mode, but I think google photos decided to be worse today. At some point batchCreate got stuck for 4 minutes, ended with EOF, did a low level retry, succeeded after 3 seconds, and only then started to commit the next batch. 

It also had files stuck at 0 bytes per second with ETAs of thousands of hours, but in the end it recovered gracefully. It's doing the rest of the files now with no issues.

Given this behavior of batchCreate, it looks plausible that this async mode helps with the "concurrent write request" rate limit of issue #6920, it really doesn't attempt to do more than one batchCreate request at once even when the server is being awful. And having comitting/committed log messages highlights that these can just take 8 seconds to complete. I get it now. It felt a bit counterintuitive but the sync mode is not afraid to start concurrent write requests (what is being blocked is the transfer, but many transfers and batches can happen in parallel), this mode avoids it.

Thanks for this feature and the bugfix!

(Also I'm preparing to move to a self-hosted thing, paying for google photos is not worth it, this API sucks)
